package dart

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writeClient generates lib/src/client/masterfabric_client.dart — a typed
// wrapper class around the graphql package's GraphQLClient.
func writeClient(schema *parser.Schema, outDir string) error {
	var b strings.Builder

	// Determine whether any operation return type or arg is a raw enum (not
	// wrapped in an object) — only then do we need to import enums.dart directly.
	needsEnumImport := false
	allOps := append(schema.Queries, schema.Mutations...)
	for _, op := range allOps {
		if isEnum(op.ReturnType, schema) {
			needsEnumImport = true
			break
		}
		for _, a := range op.Args {
			if isEnum(a.TypeName, schema) {
				needsEnumImport = true
				break
			}
		}
	}

	// Determine whether inputs.dart is needed (any op takes an input-type arg).
	needsInputImport := false
	for _, op := range allOps {
		for _, a := range op.Args {
			if isInput(a.TypeName, schema) {
				needsInputImport = true
				break
			}
		}
	}

	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate dart\n\n")
	b.WriteString("import 'package:graphql/client.dart';\n\n")
	b.WriteString("import '../models/models.dart';\n")
	if needsEnumImport {
		b.WriteString("import '../models/enums.dart';\n")
	}
	if needsInputImport {
		b.WriteString("import '../models/inputs.dart';\n")
	}
	b.WriteString("import '../queries/documents.dart';\n\n")

	// Exception class
	b.WriteString(`/// Thrown when the server returns a non-null errors array.
class MasterFabricException implements Exception {
  final List<GraphQLError> errors;
  const MasterFabricException(this.errors);

  @override
  String toString() =>
      'MasterFabricException: ${errors.map((e) => e.message).join(', ')}';
}

`)

	// Client class header
	b.WriteString("/// Typed GraphQL client for the MasterFabric API.\n")
	b.WriteString("///\n")
	b.WriteString("/// Instantiate once and share across your app (e.g. via Provider / Riverpod).\n")
	b.WriteString("///\n")
	b.WriteString("/// Example:\n")
	b.WriteString("/// ```dart\n")
	b.WriteString("/// final client = MasterFabricClient(\n")
	b.WriteString("///   graphqlEndpoint: 'http://localhost:8080/graphql',\n")
	b.WriteString("/// );\n")
	b.WriteString("/// final payload = await client.register(\n")
	b.WriteString("///   input: RegisterInput(\n")
	b.WriteString("///     email: 'user@example.com',\n")
	b.WriteString("///     password: 'secret',\n")
	b.WriteString("///     displayName: 'Alice',\n")
	b.WriteString("///   ),\n")
	b.WriteString("/// );\n")
	b.WriteString("/// ```\n")
	b.WriteString("class MasterFabricClient {\n")
	b.WriteString("  late final GraphQLClient _client;\n\n")
	b.WriteString("  MasterFabricClient({\n")
	b.WriteString("    required String graphqlEndpoint,\n")
	b.WriteString("    String? authToken,\n")
	b.WriteString("    GraphQLClient? client,\n")
	b.WriteString("  }) {\n")
	b.WriteString("    if (client != null) {\n")
	b.WriteString("      _client = client;\n")
	b.WriteString("      return;\n")
	b.WriteString("    }\n")
	b.WriteString("    final httpLink = HttpLink(graphqlEndpoint);\n")
	b.WriteString("    final Link link;\n")
	b.WriteString("    if (authToken != null) {\n")
	b.WriteString("      final authLink = AuthLink(getToken: () => 'Bearer $authToken');\n")
	b.WriteString("      link = authLink.concat(httpLink);\n")
	b.WriteString("    } else {\n")
	b.WriteString("      link = httpLink;\n")
	b.WriteString("    }\n")
	b.WriteString("    _client = GraphQLClient(\n")
	b.WriteString("      link: link,\n")
	b.WriteString("      cache: GraphQLCache(),\n")
	b.WriteString("    );\n")
	b.WriteString("  }\n\n")
	b.WriteString("  /// Replace the auth token (e.g. after login / token refresh).\n")
	b.WriteString("  MasterFabricClient withToken(String token) => MasterFabricClient(\n")
	b.WriteString("        graphqlEndpoint: '',\n")
	b.WriteString("        client: GraphQLClient(\n")
	b.WriteString("          link: AuthLink(getToken: () => 'Bearer $token')\n")
	b.WriteString("              .concat(_client.link),\n")
	b.WriteString("          cache: _client.cache,\n")
	b.WriteString("        ),\n")
	b.WriteString("      );\n\n")

	// Generate query methods
	for _, q := range schema.Queries {
		if isIntrospectionField(q.Name) {
			continue
		}
		b.WriteString(buildQueryMethod(q, schema))
		b.WriteString("\n")
	}

	// Generate mutation methods
	for _, m := range schema.Mutations {
		if isIntrospectionField(m.Name) {
			continue
		}
		b.WriteString(buildMutationMethod(m, schema))
		b.WriteString("\n")
	}

	// Close class
	b.WriteString("  // ── Internal helpers ──────────────────────────────────────────────────\n\n")
	b.WriteString(`  void _throwIfErrors(QueryResult result) {
    if (result.hasException) {
      final gqlErrors = result.exception?.graphqlErrors ?? [];
      if (gqlErrors.isNotEmpty) throw MasterFabricException(gqlErrors);
      throw result.exception!;
    }
  }
}
`)

	path := filepath.Join(outDir, "lib", "src", "client", "masterfabric_client.dart")
	return writeFile(path, b.String())
}

// ── Method builders ──────────────────────────────────────────────────────────

func buildQueryMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnDart := operationReturnType(op, schema)
	params := buildDartParams(op.Args, schema)
	constName := toConstName(op.Name) + "Query"

	b.WriteString(fmt.Sprintf("  /// Query: %s\n", op.Name))
	b.WriteString(fmt.Sprintf("  Future<%s> %s(%s) async {\n", returnDart, toCamelCase(op.Name), params))
	b.WriteString(fmt.Sprintf("    final result = await _client.query(\n"))
	b.WriteString(fmt.Sprintf("      QueryOptions(\n"))
	b.WriteString(fmt.Sprintf("        document: %s,\n", constName))
	if len(op.Args) > 0 {
		b.WriteString(fmt.Sprintf("        variables: %s,\n", buildVariablesMap(op.Args, schema)))
	}
	b.WriteString("      ),\n")
	b.WriteString("    );\n")
	b.WriteString("    _throwIfErrors(result);\n")
	b.WriteString(fmt.Sprintf("    final data = result.data!['%s'];\n", op.Name))
	b.WriteString(fmt.Sprintf("    return %s;\n", parseResultExpr(op, schema)))
	b.WriteString("  }\n")
	return b.String()
}

func buildMutationMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnDart := operationReturnType(op, schema)
	params := buildDartParams(op.Args, schema)
	constName := toConstName(op.Name) + "Mutation"

	b.WriteString(fmt.Sprintf("  /// Mutation: %s\n", op.Name))
	b.WriteString(fmt.Sprintf("  Future<%s> %s(%s) async {\n", returnDart, toCamelCase(op.Name), params))
	b.WriteString("    final result = await _client.mutate(\n")
	b.WriteString("      MutationOptions(\n")
	b.WriteString(fmt.Sprintf("        document: %s,\n", constName))
	if len(op.Args) > 0 {
		b.WriteString(fmt.Sprintf("        variables: %s,\n", buildVariablesMap(op.Args, schema)))
	}
	b.WriteString("      ),\n")
	b.WriteString("    );\n")
	b.WriteString("    _throwIfErrors(result);\n")
	b.WriteString(fmt.Sprintf("    final data = result.data!['%s'];\n", op.Name))
	b.WriteString(fmt.Sprintf("    return %s;\n", parseResultExpr(op, schema)))
	b.WriteString("  }\n")
	return b.String()
}

// operationReturnType returns the Dart return type for a Future<T>.
func operationReturnType(op *parser.Operation, schema *parser.Schema) string {
	if op.ReturnType == "" || op.ReturnType == "Boolean" {
		if op.ReturnNull {
			return "bool?"
		}
		return "bool"
	}
	if isScalar(op.ReturnType) {
		base := gqlToDartBase(op.ReturnType)
		if op.ReturnList {
			return fmt.Sprintf("List<%s>", base)
		}
		if op.ReturnNull {
			return base + "?"
		}
		return base
	}
	base := op.ReturnType
	if op.ReturnList {
		return fmt.Sprintf("List<%s>", base)
	}
	if op.ReturnNull {
		return base + "?"
	}
	return base
}

// buildDartParams builds the Dart method parameter list for an operation.
func buildDartParams(args []*parser.Argument, schema *parser.Schema) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		dartType := argDartType(a, schema)
		if a.NonNull {
			parts = append(parts, fmt.Sprintf("required %s %s", dartType, toCamelCase(a.Name)))
		} else {
			parts = append(parts, fmt.Sprintf("%s %s", dartType, toCamelCase(a.Name)))
		}
	}
	return "{\n    " + strings.Join(parts, ",\n    ") + ",\n  }"
}

func argDartType(a *parser.Argument, schema *parser.Schema) string {
	if isScalar(a.TypeName) {
		return gqlToDart(a.TypeName, a.NonNull)
	}
	// Input type or enum
	if a.NonNull {
		return a.TypeName
	}
	return a.TypeName + "?"
}

// buildVariablesMap builds the variables map literal for the GraphQL request.
// Each argument needs a type-appropriate serialisation expression:
//   - Input types  → name.toJson()           (they have a toJson method)
//   - Enums        → name.value              (extension getter from enums.dart)
//   - Nullable enum → name?.value            (guard against null)
//   - Scalars      → name                    (String/bool/int/double pass through)
//   - Nullable scalars that must be omitted when null are wrapped in collection-if
func buildVariablesMap(args []*parser.Argument, schema *parser.Schema) string {
	var parts []string
	for _, a := range args {
		name := toCamelCase(a.Name)
		var expr string
		switch {
		case isInput(a.TypeName, schema):
			if a.NonNull {
				expr = fmt.Sprintf("'%s': %s.toJson()", a.Name, name)
			} else {
				// Nullable input — only include key when non-null
				expr = fmt.Sprintf("if (%s != null) '%s': %s!.toJson()", name, a.Name, name)
			}
		case isEnum(a.TypeName, schema):
			if a.NonNull {
				expr = fmt.Sprintf("'%s': %s.value", a.Name, name)
			} else {
				expr = fmt.Sprintf("if (%s != null) '%s': %s!.value", name, a.Name, name)
			}
		default:
			// Scalar (String, bool, int, double, UUID, …)
			if a.NonNull {
				expr = fmt.Sprintf("'%s': %s", a.Name, name)
			} else {
				// Nullable scalar — omit the key entirely when null so the
				// server receives no variable (rather than explicit null).
				expr = fmt.Sprintf("if (%s != null) '%s': %s", name, a.Name, name)
			}
		}
		parts = append(parts, expr)
	}
	return "{\n          " + strings.Join(parts, ",\n          ") + ",\n        }"
}

// parseResultExpr generates the Dart expression to deserialise `data` into the return type.
func parseResultExpr(op *parser.Operation, schema *parser.Schema) string {
	if op.ReturnType == "" || op.ReturnType == "Boolean" {
		return "data as bool"
	}
	if isScalar(op.ReturnType) {
		return fmt.Sprintf("data as %s", gqlToDartBase(op.ReturnType))
	}
	if isObject(op.ReturnType, schema) {
		if op.ReturnList {
			return fmt.Sprintf("(data as List<dynamic>).map((e) => %s.fromJson(e as Map<String, dynamic>)).toList()", op.ReturnType)
		}
		return fmt.Sprintf("%s.fromJson(data as Map<String, dynamic>)", op.ReturnType)
	}
	if isEnum(op.ReturnType, schema) {
		return fmt.Sprintf("%sX.fromValue(data as String)", op.ReturnType)
	}
	return "data"
}
