package dart

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// ── Type mapping ─────────────────────────────────────────────────────────────

// gqlToDart converts a GraphQL type name to a Dart type.
func gqlToDart(typeName string, nonNull bool) string {
	base := gqlToDartBase(typeName)
	if !nonNull {
		return base + "?"
	}
	return base
}

func gqlToDartBase(typeName string) string {
	switch typeName {
	case "String", "UUID", "ID":
		return "String"
	case "Int":
		return "int"
	case "Float":
		return "double"
	case "Boolean":
		return "bool"
	case "Time":
		return "DateTime"
	default:
		return typeName // named model / enum — keep as-is
	}
}

// isScalar returns true for types that don't get their own model file.
func isScalar(typeName string) bool {
	switch typeName {
	case "String", "UUID", "ID", "Int", "Float", "Boolean", "Time":
		return true
	}
	return false
}

// toCamelCase converts snake_case / camelCase names to lowerCamelCase Dart field names.
func toCamelCase(s string) string {
	// Already camelCase from GraphQL — just lower-case first letter.
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// toSnakeCase converts camelCase to snake_case for Dart file names.
func toSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteRune('_')
		}
		b.WriteRune(r)
	}
	return strings.ToLower(b.String())
}

// screamingToCamel converts SCREAMING_SNAKE_CASE → lowerCamelCase.
// e.g. ACTIVE → active, INACTIVE → inactive, LIGHT → light, DARK → dark.
func screamingToCamel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	if len(parts) == 1 {
		return parts[0]
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(p)
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}

// ── Enums ────────────────────────────────────────────────────────────────────

func writeEnums(schema *parser.Schema, outDir string) error {
	if len(schema.Enums) == 0 {
		return nil
	}

	// Sort for stable output
	enums := make([]*parser.EnumType, len(schema.Enums))
	copy(enums, schema.Enums)
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate dart\n\n")

	for _, e := range enums {
		b.WriteString(fmt.Sprintf("enum %s {\n", e.Name))
		for _, v := range e.Values {
			// GraphQL enum values are SCREAMING_SNAKE_CASE; convert to lowerCamelCase.
			b.WriteString(fmt.Sprintf("  %s,\n", screamingToCamel(v)))
		}
		b.WriteString("}\n\n")
		// Extension for serialisation
		b.WriteString(fmt.Sprintf("extension %sX on %s {\n", e.Name, e.Name))
		b.WriteString("  // Converts the Dart enum value back to the GraphQL string the server expects.\n")
		b.WriteString("  String get value {\n")
		b.WriteString("    switch (this) {\n")
		for _, v := range e.Values {
			dartVal := screamingToCamel(v)
			b.WriteString(fmt.Sprintf("      case %s.%s: return '%s';\n", e.Name, dartVal, v))
		}
		b.WriteString("    }\n")
		b.WriteString("  }\n\n")
		b.WriteString(fmt.Sprintf("  static %s fromValue(String v) {\n", e.Name))
		b.WriteString("    switch (v) {\n")
		for _, v := range e.Values {
			dartVal := screamingToCamel(v)
			b.WriteString(fmt.Sprintf("      case '%s': return %s.%s;\n", v, e.Name, dartVal))
		}
		b.WriteString(fmt.Sprintf("      default: throw ArgumentError('Unknown %s value: $v');\n", e.Name))
		b.WriteString("    }\n")
		b.WriteString("  }\n")
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "lib", "src", "models", "enums.dart")
	return writeFile(path, b.String())
}

// ── Inputs ───────────────────────────────────────────────────────────────────

func writeInputs(schema *parser.Schema, outDir string) error {
	if len(schema.Inputs) == 0 {
		return nil
	}

	inputs := make([]*parser.InputType, len(schema.Inputs))
	copy(inputs, schema.Inputs)
	sort.Slice(inputs, func(i, j int) bool { return inputs[i].Name < inputs[j].Name })

	// Determine if any input field references an enum — if so we need the import.
	needsEnumImport := false
	for _, inp := range inputs {
		for _, f := range inp.Fields {
			if isEnum(f.TypeName, schema) {
				needsEnumImport = true
				break
			}
		}
		if needsEnumImport {
			break
		}
	}

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate dart\n\n")
	if needsEnumImport {
		b.WriteString("import 'enums.dart';\n\n")
	}

	for _, inp := range inputs {
		b.WriteString(fmt.Sprintf("class %s {\n", inp.Name))
		// Fields
		for _, f := range inp.Fields {
			dartType := gqlToDart(f.TypeName, f.NonNull)
			if f.IsList {
				if f.NonNull {
					dartType = fmt.Sprintf("List<%s>", gqlToDartBase(f.TypeName))
				} else {
					dartType = fmt.Sprintf("List<%s>?", gqlToDartBase(f.TypeName))
				}
			}
			b.WriteString(fmt.Sprintf("  final %s %s;\n", dartType, toCamelCase(f.Name)))
		}
		b.WriteString("\n")

		// Constructor
		b.WriteString(fmt.Sprintf("  const %s({\n", inp.Name))
		for _, f := range inp.Fields {
			if f.NonNull {
				b.WriteString(fmt.Sprintf("    required this.%s,\n", toCamelCase(f.Name)))
			} else {
				b.WriteString(fmt.Sprintf("    this.%s,\n", toCamelCase(f.Name)))
			}
		}
		b.WriteString("  });\n\n")

		// toJson
		b.WriteString("  Map<String, dynamic> toJson() => {\n")
		for _, f := range inp.Fields {
			fieldName := toCamelCase(f.Name)
			if isEnum(f.TypeName, schema) {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("    '%s': %s.value,\n", f.Name, fieldName))
				} else {
					b.WriteString(fmt.Sprintf("    if (%s != null) '%s': %s!.value,\n", fieldName, f.Name, fieldName))
				}
			} else if f.TypeName == "Time" {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("    '%s': %s.toIso8601String(),\n", f.Name, fieldName))
				} else {
					b.WriteString(fmt.Sprintf("    if (%s != null) '%s': %s!.toIso8601String(),\n", fieldName, f.Name, fieldName))
				}
			} else {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("    '%s': %s,\n", f.Name, fieldName))
				} else {
					b.WriteString(fmt.Sprintf("    if (%s != null) '%s': %s,\n", fieldName, f.Name, fieldName))
				}
			}
		}
		b.WriteString("  };\n")
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "lib", "src", "models", "inputs.dart")
	return writeFile(path, b.String())
}

// ── Objects ──────────────────────────────────────────────────────────────────

func writeObjects(schema *parser.Schema, outDir string) error {
	objects := make([]*parser.ObjectType, len(schema.Objects))
	copy(objects, schema.Objects)
	sort.Slice(objects, func(i, j int) bool { return objects[i].Name < objects[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate dart\n\n")
	b.WriteString("import 'enums.dart';\n\n")

	for _, obj := range objects {
		b.WriteString(fmt.Sprintf("class %s {\n", obj.Name))
		// Fields
		for _, f := range obj.Fields {
			dartType := fieldDartType(f, schema)
			b.WriteString(fmt.Sprintf("  final %s %s;\n", dartType, toCamelCase(f.Name)))
		}
		b.WriteString("\n")

		// Constructor
		b.WriteString(fmt.Sprintf("  const %s({\n", obj.Name))
		for _, f := range obj.Fields {
			if f.NonNull {
				b.WriteString(fmt.Sprintf("    required this.%s,\n", toCamelCase(f.Name)))
			} else {
				b.WriteString(fmt.Sprintf("    this.%s,\n", toCamelCase(f.Name)))
			}
		}
		b.WriteString("  });\n\n")

		// fromJson factory
		b.WriteString(fmt.Sprintf("  factory %s.fromJson(Map<String, dynamic> json) {\n", obj.Name))
		b.WriteString(fmt.Sprintf("    return %s(\n", obj.Name))
		for _, f := range obj.Fields {
			fieldName := toCamelCase(f.Name)
			b.WriteString(fmt.Sprintf("      %s: %s,\n", fieldName, fromJsonExpr(f, schema)))
		}
		b.WriteString("    );\n")
		b.WriteString("  }\n\n")

		// toJson
		b.WriteString("  Map<String, dynamic> toJson() => {\n")
		for _, f := range obj.Fields {
			fieldName := toCamelCase(f.Name)
			b.WriteString(fmt.Sprintf("    '%s': %s,\n", f.Name, toJsonExpr(f, fieldName, schema)))
		}
		b.WriteString("  };\n")
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "lib", "src", "models", "models.dart")
	return writeFile(path, b.String())
}

// ── Helpers ──────────────────────────────────────────────────────────────────

func isEnum(typeName string, schema *parser.Schema) bool {
	for _, e := range schema.Enums {
		if e.Name == typeName {
			return true
		}
	}
	return false
}

func isObject(typeName string, schema *parser.Schema) bool {
	for _, o := range schema.Objects {
		if o.Name == typeName {
			return true
		}
	}
	return false
}

func isInput(typeName string, schema *parser.Schema) bool {
	for _, i := range schema.Inputs {
		if i.Name == typeName {
			return true
		}
	}
	return false
}

func fieldDartType(f *parser.Field, schema *parser.Schema) string {
	if f.IsList {
		inner := gqlToDartBase(f.TypeName)
		if f.NonNull {
			return fmt.Sprintf("List<%s>", inner)
		}
		return fmt.Sprintf("List<%s>?", inner)
	}
	return gqlToDart(f.TypeName, f.NonNull)
}

func fromJsonExpr(f *parser.Field, schema *parser.Schema) string {
	jsonKey := f.Name
	fieldName := toCamelCase(f.Name)
	_ = fieldName

	if f.IsList {
		inner := f.TypeName
		if isObject(inner, schema) {
			expr := fmt.Sprintf("(json['%s'] as List<dynamic>).map((e) => %s.fromJson(e as Map<String, dynamic>)).toList()", jsonKey, inner)
			if !f.NonNull {
				return fmt.Sprintf("json['%s'] == null ? null : %s", jsonKey, expr)
			}
			return expr
		}
		if isEnum(inner, schema) {
			expr := fmt.Sprintf("(json['%s'] as List<dynamic>).map((e) => %sX.fromValue(e as String)).toList()", jsonKey, inner)
			if !f.NonNull {
				return fmt.Sprintf("json['%s'] == null ? null : %s", jsonKey, expr)
			}
			return expr
		}
		if !f.NonNull {
			return fmt.Sprintf("(json['%s'] as List<dynamic>?)?.cast<%s>()", jsonKey, gqlToDartBase(inner))
		}
		return fmt.Sprintf("(json['%s'] as List<dynamic>).cast<%s>()", jsonKey, gqlToDartBase(inner))
	}

	switch f.TypeName {
	case "Time":
		if f.NonNull {
			return fmt.Sprintf("DateTime.parse(json['%s'] as String)", jsonKey)
		}
		return fmt.Sprintf("json['%s'] == null ? null : DateTime.parse(json['%s'] as String)", jsonKey, jsonKey)
	case "Boolean":
		if f.NonNull {
			return fmt.Sprintf("json['%s'] as bool", jsonKey)
		}
		return fmt.Sprintf("json['%s'] as bool?", jsonKey)
	case "Int":
		if f.NonNull {
			return fmt.Sprintf("json['%s'] as int", jsonKey)
		}
		return fmt.Sprintf("json['%s'] as int?", jsonKey)
	case "Float":
		if f.NonNull {
			return fmt.Sprintf("json['%s'] as double", jsonKey)
		}
		return fmt.Sprintf("json['%s'] as double?", jsonKey)
	}

	if isEnum(f.TypeName, schema) {
		if f.NonNull {
			return fmt.Sprintf("%sX.fromValue(json['%s'] as String)", f.TypeName, jsonKey)
		}
		return fmt.Sprintf("json['%s'] == null ? null : %sX.fromValue(json['%s'] as String)", jsonKey, f.TypeName, jsonKey)
	}
	if isObject(f.TypeName, schema) {
		if f.NonNull {
			return fmt.Sprintf("%s.fromJson(json['%s'] as Map<String, dynamic>)", f.TypeName, jsonKey)
		}
		return fmt.Sprintf("json['%s'] == null ? null : %s.fromJson(json['%s'] as Map<String, dynamic>)", jsonKey, f.TypeName, jsonKey)
	}
	// String / UUID / ID / unknown
	if f.NonNull {
		return fmt.Sprintf("json['%s'] as String", jsonKey)
	}
	return fmt.Sprintf("json['%s'] as String?", jsonKey)
}

func toJsonExpr(f *parser.Field, fieldName string, schema *parser.Schema) string {
	if isEnum(f.TypeName, schema) {
		if f.NonNull {
			return fmt.Sprintf("%s.value", fieldName)
		}
		return fmt.Sprintf("%s?.value", fieldName)
	}
	if f.TypeName == "Time" {
		if f.NonNull {
			return fmt.Sprintf("%s.toIso8601String()", fieldName)
		}
		return fmt.Sprintf("%s?.toIso8601String()", fieldName)
	}
	if isObject(f.TypeName, schema) {
		if f.IsList {
			if f.NonNull {
				return fmt.Sprintf("%s.map((e) => e.toJson()).toList()", fieldName)
			}
			return fmt.Sprintf("%s?.map((e) => e.toJson()).toList()", fieldName)
		}
		if f.NonNull {
			return fmt.Sprintf("%s.toJson()", fieldName)
		}
		return fmt.Sprintf("%s?.toJson()", fieldName)
	}
	return fieldName
}
