package dart

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writePubspec generates pubspec.yaml for the Dart package.
func writePubspec(schema *parser.Schema, outDir string) error {
	_ = schema // not needed here, kept for consistent signature

	content := `# GENERATED CODE — DO NOT EDIT BY HAND
# Generated by masterfabric_go generate dart

name: dart_go_api
description: >-
  Auto-generated Dart/Flutter GraphQL client package for the MasterFabric API.
  Re-generate by running: masterfabric_go generate dart
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.2
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
`

	path := filepath.Join(outDir, "pubspec.yaml")
	return writeFile(path, content)
}

// writeBarrel generates lib/dart_go_api.dart — the single barrel export file.
func writeBarrel(schema *parser.Schema, outDir string) error {
	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate dart\n")
	b.WriteString(fmt.Sprintf("// Package: dart_go_api\n"))
	b.WriteString("//\n")
	b.WriteString("// Import this single file to get access to all models,\n")
	b.WriteString("// document nodes, and the typed client.\n\n")
	b.WriteString("library dart_go_api;\n\n")
	b.WriteString("// Models\n")
	b.WriteString("export 'src/models/enums.dart';\n")
	b.WriteString("export 'src/models/inputs.dart';\n")
	b.WriteString("export 'src/models/models.dart';\n\n")
	b.WriteString("// GraphQL document nodes\n")
	b.WriteString("export 'src/queries/documents.dart';\n\n")
	b.WriteString("// Typed client\n")
	b.WriteString("export 'src/client/masterfabric_client.dart';\n")

	path := filepath.Join(outDir, "lib", "dart_go_api.dart")
	return writeFile(path, b.String())
}
