package dart

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writeDocuments generates lib/src/queries/documents.dart which contains
// a gql() DocumentNode constant for every query and mutation.
func writeDocuments(schema *parser.Schema, outDir string) error {
	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate dart\n\n")
	b.WriteString("import 'package:graphql/client.dart';\n\n")

	// Queries
	for _, q := range schema.Queries {
		if isIntrospectionField(q.Name) {
			continue
		}
		constName := toConstName(q.Name) + "Query"
		selectionSet := buildSelectionSet(q.ReturnType, q.ReturnList, schema)
		gqlStr := buildQueryDocument(q, selectionSet)
		b.WriteString(fmt.Sprintf("final %s = gql(r'''\n%s\n''');\n\n", constName, gqlStr))
	}

	// Mutations
	for _, m := range schema.Mutations {
		if isIntrospectionField(m.Name) {
			continue
		}
		constName := toConstName(m.Name) + "Mutation"
		selectionSet := buildSelectionSet(m.ReturnType, m.ReturnList, schema)
		gqlStr := buildMutationDocument(m, selectionSet)
		b.WriteString(fmt.Sprintf("final %s = gql(r'''\n%s\n''');\n\n", constName, gqlStr))
	}

	path := filepath.Join(outDir, "lib", "src", "queries", "documents.dart")
	return writeFile(path, b.String())
}

// toConstName converts a lowerCamelCase operation name to a lowerCamelCase const name.
// e.g. "register" → "register", "updateProfile" → "updateProfile"
func toConstName(name string) string {
	return toCamelCase(name)
}

// buildQueryDocument emits a full query document string.
func buildQueryDocument(op *parser.Operation, selectionSet string) string {
	var b strings.Builder
	opName := strings.ToUpper(op.Name[:1]) + op.Name[1:]

	if len(op.Args) == 0 {
		b.WriteString(fmt.Sprintf("query %s {\n", opName))
		b.WriteString(fmt.Sprintf("  %s %s\n", op.Name, selectionSet))
		b.WriteString("}")
		return b.String()
	}

	// Build variable declarations + call args
	varDecls, callArgs := buildArgStrings(op.Args)
	b.WriteString(fmt.Sprintf("query %s(%s) {\n", opName, varDecls))
	b.WriteString(fmt.Sprintf("  %s(%s) %s\n", op.Name, callArgs, selectionSet))
	b.WriteString("}")
	return b.String()
}

// buildMutationDocument emits a full mutation document string.
func buildMutationDocument(op *parser.Operation, selectionSet string) string {
	var b strings.Builder
	opName := strings.ToUpper(op.Name[:1]) + op.Name[1:]

	if len(op.Args) == 0 {
		b.WriteString(fmt.Sprintf("mutation %s {\n", opName))
		b.WriteString(fmt.Sprintf("  %s %s\n", op.Name, selectionSet))
		b.WriteString("}")
		return b.String()
	}

	varDecls, callArgs := buildArgStrings(op.Args)
	b.WriteString(fmt.Sprintf("mutation %s(%s) {\n", opName, varDecls))
	b.WriteString(fmt.Sprintf("  %s(%s) %s\n", op.Name, callArgs, selectionSet))
	b.WriteString("}")
	return b.String()
}

// buildArgStrings returns ($var: Type, ...) and (arg: $var, ...) strings.
func buildArgStrings(args []*parser.Argument) (varDecls, callArgs string) {
	var decls, calls []string
	for _, a := range args {
		gqlType := dartToGqlType(a.TypeName, a.NonNull)
		decls = append(decls, fmt.Sprintf("$%s: %s", a.Name, gqlType))
		calls = append(calls, fmt.Sprintf("%s: $%s", a.Name, a.Name))
	}
	return strings.Join(decls, ", "), strings.Join(calls, ", ")
}

// dartToGqlType converts a Go-parsed type name back to a GraphQL type string.
func dartToGqlType(typeName string, nonNull bool) string {
	suffix := ""
	if nonNull {
		suffix = "!"
	}
	return typeName + suffix
}

// buildSelectionSet introspects the return type and builds a minimal selection
// set that includes all scalar fields and nested object fields (one level deep).
func buildSelectionSet(typeName string, isList bool, schema *parser.Schema) string {
	// Scalar / Boolean return
	if typeName == "" || typeName == "Boolean" || isScalar(typeName) {
		return ""
	}

	obj := findObject(typeName, schema)
	if obj == nil {
		return ""
	}

	var lines []string
	lines = append(lines, "{")
	for _, f := range obj.Fields {
		if isScalar(f.TypeName) || f.TypeName == "" {
			lines = append(lines, "    "+f.Name)
		} else {
			// One level of nesting
			nested := findObject(f.TypeName, schema)
			if nested != nil {
				lines = append(lines, "    "+f.Name+" {")
				for _, nf := range nested.Fields {
					if isScalar(nf.TypeName) || nf.TypeName == "" {
						lines = append(lines, "      "+nf.Name)
					}
				}
				lines = append(lines, "    }")
			} else {
				lines = append(lines, "    "+f.Name)
			}
		}
	}
	lines = append(lines, "  }")
	return strings.Join(lines, "\n  ")
}

func findObject(name string, schema *parser.Schema) *parser.ObjectType {
	for _, o := range schema.Objects {
		if o.Name == name {
			return o
		}
	}
	return nil
}

// isIntrospectionField returns true for built-in GraphQL introspection fields
// (__schema, __type, etc.) that should not be code-generated.
func isIntrospectionField(name string) bool {
	return len(name) > 1 && name[:2] == "__"
}
