package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	adminDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/admin/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
)

// AdminSuspendUser is the resolver for the adminSuspendUser field.
func (r *mutationResolver) AdminSuspendUser(ctx context.Context, id uuid.UUID, suspend bool) (*model.AdminUserProfile, error) {
	resp, err := r.SuspendUserUC.Execute(ctx, &adminDTO.SuspendUserRequest{
		TargetUserID: id.String(),
		Suspend:      suspend,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return adminUserToModel(resp), nil
}

// AdminChangeRole is the resolver for the adminChangeRole field.
func (r *mutationResolver) AdminChangeRole(ctx context.Context, id uuid.UUID, role model.UserRole) (*model.AdminUserProfile, error) {
	resp, err := r.ChangeRoleUC.Execute(ctx, &adminDTO.ChangeRoleRequest{
		TargetUserID: id.String(),
		Role:         graphqlRoleToString(role),
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return adminUserToModel(resp), nil
}

// AdminUsers is the resolver for the adminUsers field.
func (r *queryResolver) AdminUsers(ctx context.Context, page *int, pageSize *int) (*model.AdminUserList, error) {
	p, ps := 1, 20
	if page != nil {
		p = *page
	}
	if pageSize != nil {
		ps = *pageSize
	}
	resp, err := r.ListUsersUC.Execute(ctx, p, ps)
	if err != nil {
		return nil, mapErr(err)
	}
	users := make([]*model.AdminUserProfile, 0, len(resp.Users))
	for _, u := range resp.Users {
		users = append(users, adminUserToModel(u))
	}
	return &model.AdminUserList{
		Users:      users,
		TotalCount: resp.TotalCount,
		Page:       resp.Page,
		PageSize:   resp.PageSize,
	}, nil
}

// AdminUser is the resolver for the adminUser field.
func (r *queryResolver) AdminUser(ctx context.Context, id uuid.UUID) (*model.AdminUserProfile, error) {
	resp, err := r.GetUserByIDUC.Execute(ctx, id.String())
	if err != nil {
		return nil, mapErr(err)
	}
	return adminUserToModel(resp), nil
}
