package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	authDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/auth/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	resp, err := r.RegisterUC.Execute(ctx, &authDTO.RegisterRequest{
		Email:       input.Email,
		Password:    input.Password,
		DisplayName: input.DisplayName,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return authRespToPayload(resp), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	resp, err := r.LoginUC.Execute(ctx, &authDTO.LoginRequest{
		Email:    input.Email,
		Password: input.Password,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return authRespToPayload(resp), nil
}

// RefreshTokens is the resolver for the refreshTokens field.
func (r *mutationResolver) RefreshTokens(ctx context.Context, input model.RefreshInput) (*model.AuthPayload, error) {
	resp, err := r.RefreshUC.Execute(ctx, &authDTO.RefreshRequest{
		UserID:       input.UserID.String(),
		RefreshToken: input.RefreshToken,
	})
	if err != nil {
		return nil, mapErr(err)
	}
	return authRespToPayload(resp), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input model.LogoutInput) (bool, error) {
	err := r.LogoutUC.Execute(ctx, &authDTO.LogoutRequest{
		UserID:       input.UserID.String(),
		AccessToken:  input.AccessToken,
		RefreshToken: input.RefreshToken,
	})
	if err != nil {
		return false, mapErr(err)
	}
	return true, nil
}
