package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"

	"github.com/google/uuid"
	settingsDTO "github.com/masterfabric/masterfabric_go_basic/internal/application/settings/dto"
	"github.com/masterfabric/masterfabric_go_basic/internal/infrastructure/graphql/model"
	domainErr "github.com/masterfabric/masterfabric_go_basic/internal/shared/errors"
	"github.com/masterfabric/masterfabric_go_basic/internal/shared/middleware"
)

// UpdateMySettings is the resolver for the updateMySettings field.
func (r *mutationResolver) UpdateMySettings(ctx context.Context, input model.UserSettingsInput) (*model.UserSettingsPayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	req := &settingsDTO.UserSettingsRequest{
		UserID:          userID.String(),
		NotificationsOn: input.NotificationsOn,
	}
	if input.Theme != nil {
		t := themeToString(*input.Theme)
		req.Theme = &t
	}
	req.Language = input.Language
	req.Timezone = input.Timezone

	resp, err := r.UpdateUserSettingsUC.Execute(ctx, req)
	if err != nil {
		return nil, mapErr(err)
	}
	return settingsRespToModel(userID, resp), nil
}

// MySettings is the resolver for the mySettings field.
func (r *queryResolver) MySettings(ctx context.Context) (*model.UserSettingsPayload, error) {
	userID := middleware.UserIDFromContext(ctx)
	if userID == uuid.Nil {
		return nil, domainErr.ErrUnauthorized
	}

	resp, err := r.GetUserSettingsUC.Execute(ctx, userID.String())
	if err != nil {
		return nil, mapErr(err)
	}
	return settingsRespToModel(userID, resp), nil
}

// AppSettings is the resolver for the appSettings field.
func (r *queryResolver) AppSettings(ctx context.Context) ([]*model.AppSetting, error) {
	items, err := r.GetAppSettingsUC.Execute(ctx)
	if err != nil {
		return nil, mapErr(err)
	}
	result := make([]*model.AppSetting, 0, len(items))
	for _, s := range items {
		result = append(result, &model.AppSetting{
			Key:         s.Key,
			Value:       s.Value,
			Description: s.Description,
		})
	}
	return result, nil
}
