package kotlin

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writeClient generates client/MasterFabricClient.kt — a typed coroutine-based
// GraphQL client using OkHttp + Gson for serialisation. No Apollo runtime needed.
func writeClient(schema *parser.Schema, outDir string) error {
	var b strings.Builder

	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate kotlin\n\n")
	b.WriteString("package com.masterfabric.api.client\n\n")
	b.WriteString("import com.google.gson.Gson\n")
	b.WriteString("import com.google.gson.reflect.TypeToken\n")
	b.WriteString("import com.masterfabric.api.models.*\n")
	b.WriteString("import com.masterfabric.api.queries.MasterFabricDocuments\n")
	b.WriteString("import kotlinx.coroutines.Dispatchers\n")
	b.WriteString("import kotlinx.coroutines.withContext\n")
	b.WriteString("import okhttp3.MediaType.Companion.toMediaType\n")
	b.WriteString("import okhttp3.OkHttpClient\n")
	b.WriteString("import okhttp3.Request\n")
	b.WriteString("import okhttp3.RequestBody.Companion.toRequestBody\n\n")

	// ── Error types ───────────────────────────────────────────────────────────
	b.WriteString(`/** A single GraphQL error returned by the server. */
data class GraphQLErrorDetail(
    val message: String,
    val locations: List<Map<String, Int>>? = null,
    val path: List<String>? = null
)

/** Thrown when the server returns a non-empty errors array. */
class MasterFabricException(val errors: List<GraphQLErrorDetail>) :
    Exception(errors.joinToString("; ") { it.message })

`)

	// ── Client class ──────────────────────────────────────────────────────────
	b.WriteString("/**\n")
	b.WriteString(" * Typed coroutine GraphQL client for the MasterFabric API.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Instantiate once and share across your app (e.g. via Hilt / Koin).\n")
	b.WriteString(" *\n")
	b.WriteString(" * Example:\n")
	b.WriteString(" * ```kotlin\n")
	b.WriteString(" * val client = MasterFabricClient(endpoint = \"http://localhost:8080/graphql\")\n")
	b.WriteString(" * val payload = client.register(input = RegisterInput(\n")
	b.WriteString(" *     email = \"user@example.com\", password = \"secret\", displayName = \"Alice\"\n")
	b.WriteString(" * ))\n")
	b.WriteString(" * ```\n")
	b.WriteString(" */\n")
	b.WriteString("class MasterFabricClient(\n")
	b.WriteString("    private val endpoint: String,\n")
	b.WriteString("    private var authToken: String? = null,\n")
	b.WriteString("    private val httpClient: OkHttpClient = OkHttpClient()\n")
	b.WriteString(") {\n")
	b.WriteString("    private val gson = Gson()\n")
	b.WriteString("    private val jsonMediaType = \"application/json; charset=utf-8\".toMediaType()\n\n")

	b.WriteString("    /** Returns a new client with the given auth token (e.g. after login / token refresh). */\n")
	b.WriteString("    fun withToken(token: String): MasterFabricClient =\n")
	b.WriteString("        MasterFabricClient(endpoint = endpoint, authToken = token, httpClient = httpClient)\n\n")

	// Generate query methods
	for _, q := range schema.Queries {
		if isIntrospectionField(q.Name) {
			continue
		}
		b.WriteString(buildKotlinQueryMethod(q, schema))
		b.WriteString("\n")
	}

	// Generate mutation methods
	for _, m := range schema.Mutations {
		if isIntrospectionField(m.Name) {
			continue
		}
		b.WriteString(buildKotlinMutationMethod(m, schema))
		b.WriteString("\n")
	}

	// Private execute helper
	b.WriteString("    // ── Private helpers ───────────────────────────────────────────────────\n\n")
	b.WriteString(buildKotlinExecuteHelper())

	b.WriteString("}\n")

	path := filepath.Join(outDir, srcRoot, "client", "MasterFabricClient.kt")
	return writeFile(path, b.String())
}

// ── Method builders ───────────────────────────────────────────────────────────

func buildKotlinQueryMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnKt := kotlinReturnType(op, schema)
	constName := toKotlinConstName(op.Name) + "Query"

	b.WriteString(fmt.Sprintf("    /** Query: %s */\n", op.Name))
	params := buildKotlinParams(op.Args, schema)
	if params == "" {
		b.WriteString(fmt.Sprintf("    suspend fun %s(): %s {\n", toCamelCase(op.Name), returnKt))
	} else {
		b.WriteString(fmt.Sprintf("    suspend fun %s(\n%s\n    ): %s {\n", toCamelCase(op.Name), params, returnKt))
	}
	b.WriteString(fmt.Sprintf("        val query = MasterFabricDocuments.%s\n", constName))
	b.WriteString(buildKotlinVariablesBlock(op.Args, schema))
	b.WriteString(fmt.Sprintf("        return execute(query = query, variables = variables, dataKey = %q)\n", op.Name))
	b.WriteString("    }\n")
	return b.String()
}

func buildKotlinMutationMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnKt := kotlinReturnType(op, schema)
	constName := toKotlinConstName(op.Name) + "Mutation"

	b.WriteString(fmt.Sprintf("    /** Mutation: %s */\n", op.Name))
	params := buildKotlinParams(op.Args, schema)
	if params == "" {
		b.WriteString(fmt.Sprintf("    suspend fun %s(): %s {\n", toCamelCase(op.Name), returnKt))
	} else {
		b.WriteString(fmt.Sprintf("    suspend fun %s(\n%s\n    ): %s {\n", toCamelCase(op.Name), params, returnKt))
	}
	b.WriteString(fmt.Sprintf("        val query = MasterFabricDocuments.%s\n", constName))
	b.WriteString(buildKotlinVariablesBlock(op.Args, schema))
	b.WriteString(fmt.Sprintf("        return execute(query = query, variables = variables, dataKey = %q)\n", op.Name))
	b.WriteString("    }\n")
	return b.String()
}

// kotlinReturnType returns the Kotlin return type for a suspend fun.
func kotlinReturnType(op *parser.Operation, schema *parser.Schema) string {
	if op.ReturnType == "" || op.ReturnType == "Boolean" {
		if op.ReturnNull {
			return "Boolean?"
		}
		return "Boolean"
	}
	if isScalar(op.ReturnType) {
		base := gqlToKotlinBase(op.ReturnType)
		if op.ReturnList {
			return fmt.Sprintf("List<%s>", base)
		}
		if op.ReturnNull {
			return base + "?"
		}
		return base
	}
	base := op.ReturnType
	if op.ReturnList {
		return fmt.Sprintf("List<%s>", base)
	}
	if op.ReturnNull {
		return base + "?"
	}
	return base
}

// buildKotlinParams builds the Kotlin function parameter list.
func buildKotlinParams(args []*parser.Argument, schema *parser.Schema) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		ktType := argKotlinType(a, schema)
		defaultVal := ""
		if !a.NonNull {
			defaultVal = " = null"
		}
		parts = append(parts, fmt.Sprintf("        %s: %s%s", toCamelCase(a.Name), ktType, defaultVal))
	}
	return strings.Join(parts, ",\n")
}

func argKotlinType(a *parser.Argument, schema *parser.Schema) string {
	if isScalar(a.TypeName) {
		return gqlToKotlin(a.TypeName, a.NonNull)
	}
	if a.NonNull {
		return a.TypeName
	}
	return a.TypeName + "?"
}

// buildKotlinVariablesBlock emits the variables map for the request.
func buildKotlinVariablesBlock(args []*parser.Argument, schema *parser.Schema) string {
	if len(args) == 0 {
		return "        val variables: Map<String, Any?> = emptyMap()\n"
	}
	var b strings.Builder
	b.WriteString("        val variables: Map<String, Any?> = buildMap {\n")
	for _, a := range args {
		name := toCamelCase(a.Name)
		if isInput(a.TypeName, schema) {
			if a.NonNull {
				b.WriteString(fmt.Sprintf("            put(%q, %s.toVariables())\n", a.Name, name))
			} else {
				b.WriteString(fmt.Sprintf("            %s?.let { put(%q, it.toVariables()) }\n", name, a.Name))
			}
		} else if isEnum(a.TypeName, schema) {
			if a.NonNull {
				b.WriteString(fmt.Sprintf("            put(%q, %s.value)\n", a.Name, name))
			} else {
				b.WriteString(fmt.Sprintf("            %s?.let { put(%q, it.value) }\n", name, a.Name))
			}
		} else {
			if a.NonNull {
				b.WriteString(fmt.Sprintf("            put(%q, %s)\n", a.Name, name))
			} else {
				b.WriteString(fmt.Sprintf("            %s?.let { put(%q, it) }\n", name, a.Name))
			}
		}
	}
	b.WriteString("        }\n")
	return b.String()
}

// buildKotlinExecuteHelper emits the private generic execute suspend function.
func buildKotlinExecuteHelper() string {
	return `    private suspend inline fun <reified T> execute(
        query: String,
        variables: Map<String, Any?>,
        dataKey: String
    ): T = withContext(Dispatchers.IO) {
        val body = gson.toJson(mapOf("query" to query, "variables" to variables))
        val request = Request.Builder()
            .url(endpoint)
            .post(body.toRequestBody(jsonMediaType))
            .header("Content-Type", "application/json")
            .apply { authToken?.let { header("Authorization", "Bearer $it") } }
            .build()

        val response = httpClient.newCall(request).execute()
        val responseBody = response.body?.string() ?: error("Empty response body")

        @Suppress("UNCHECKED_CAST")
        val root = gson.fromJson(responseBody, Map::class.java) as Map<String, Any?>

        val errors = root["errors"]
        if (errors is List<*> && errors.isNotEmpty()) {
            val errJson = gson.toJson(mapOf("errors" to errors))
            val type = object : TypeToken<Map<String, List<GraphQLErrorDetail>>>() {}.type
            val parsed: Map<String, List<GraphQLErrorDetail>> = gson.fromJson(errJson, type)
            throw MasterFabricException(parsed["errors"] ?: emptyList())
        }

        @Suppress("UNCHECKED_CAST")
        val data = (root["data"] as? Map<String, Any?>)
            ?: error("No data in response")
        val field = data[dataKey] ?: error("Missing field '$dataKey' in response data")

        val fieldJson = gson.toJson(field)
        gson.fromJson(fieldJson, T::class.java)
    }

`
}
