package kotlin

import (
	"path/filepath"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writeBuildGradle generates build.gradle.kts for the Kotlin Android library.
func writeBuildGradle(_ *parser.Schema, outDir string) error {
	content := `// GENERATED CODE — DO NOT EDIT BY HAND
// Generated by masterfabric_go generate kotlin

plugins {
    id("com.android.library") version "8.2.0"
    id("org.jetbrains.kotlin.android") version "1.9.22"
}

android {
    namespace = "com.masterfabric.api"
    compileSdk = 34

    defaultConfig {
        minSdk = 24
        targetSdk = 34
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")

    // HTTP client
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // JSON serialisation
    implementation("com.google.code.gson:gson:2.10.1")

    // Java 8+ time API back-compat on older Android
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")
}
`
	path := filepath.Join(outDir, "build.gradle.kts")
	return writeFile(path, content)
}
