package kotlin

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// ── Type mapping ──────────────────────────────────────────────────────────────

// gqlToKotlin converts a GraphQL type name to a Kotlin type.
func gqlToKotlin(typeName string, nonNull bool) string {
	base := gqlToKotlinBase(typeName)
	if !nonNull {
		return base + "?"
	}
	return base
}

func gqlToKotlinBase(typeName string) string {
	switch typeName {
	case "String", "UUID", "ID":
		return "String"
	case "Int":
		return "Int"
	case "Float":
		return "Double"
	case "Boolean":
		return "Boolean"
	case "Time":
		return "java.time.Instant"
	default:
		return typeName
	}
}

// isScalar returns true for GraphQL built-in scalar types.
func isScalar(typeName string) bool {
	switch typeName {
	case "String", "UUID", "ID", "Int", "Float", "Boolean", "Time":
		return true
	}
	return false
}

// isEnum returns true if typeName is an enum in the schema.
func isEnum(typeName string, schema *parser.Schema) bool {
	for _, e := range schema.Enums {
		if e.Name == typeName {
			return true
		}
	}
	return false
}

// isObject returns true if typeName is an object type in the schema.
func isObject(typeName string, schema *parser.Schema) bool {
	for _, o := range schema.Objects {
		if o.Name == typeName {
			return true
		}
	}
	return false
}

// isInput returns true if typeName is an input type in the schema.
func isInput(typeName string, schema *parser.Schema) bool {
	for _, i := range schema.Inputs {
		if i.Name == typeName {
			return true
		}
	}
	return false
}

// isIntrospectionField returns true for built-in GraphQL introspection fields.
func isIntrospectionField(name string) bool {
	return len(name) > 1 && name[:2] == "__"
}

// toCamelCase lower-cases the first letter.
func toCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// screamingToCamel converts SCREAMING_SNAKE_CASE → lowerCamelCase.
func screamingToCamel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	if len(parts) == 1 {
		return parts[0]
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(p)
		} else {
			if len(p) > 0 {
				b.WriteString(strings.ToUpper(p[:1]) + p[1:])
			}
		}
	}
	return b.String()
}

// fieldKotlinType returns the full Kotlin type for a field.
func fieldKotlinType(f *parser.Field) string {
	if f.IsList {
		inner := gqlToKotlinBase(f.TypeName)
		if f.NonNull {
			return fmt.Sprintf("List<%s>", inner)
		}
		return fmt.Sprintf("List<%s>?", inner)
	}
	return gqlToKotlin(f.TypeName, f.NonNull)
}

// ── Enums ─────────────────────────────────────────────────────────────────────

func writeEnums(schema *parser.Schema, outDir string) error {
	if len(schema.Enums) == 0 {
		return nil
	}

	enums := make([]*parser.EnumType, len(schema.Enums))
	copy(enums, schema.Enums)
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate kotlin\n\n")
	b.WriteString("package com.masterfabric.api.models\n\n")
	b.WriteString("import com.google.gson.annotations.SerializedName\n\n")

	for _, e := range enums {
		b.WriteString(fmt.Sprintf("/** GraphQL enum: %s */\n", e.Name))
		b.WriteString(fmt.Sprintf("enum class %s(val value: String) {\n", e.Name))
		for i, v := range e.Values {
			camelVal := screamingToCamel(v)
			// Capitalise first letter for Kotlin enum entry convention
			entryName := strings.ToUpper(camelVal[:1]) + camelVal[1:]
			comma := ","
			if i == len(e.Values)-1 {
				comma = ";"
			}
			b.WriteString(fmt.Sprintf("    @SerializedName(%q)\n", v))
			b.WriteString(fmt.Sprintf("    %s(%q)%s\n", entryName, v, comma))
		}
		b.WriteString("\n")
		b.WriteString("    companion object {\n")
		b.WriteString(fmt.Sprintf("        fun fromValue(v: String): %s =\n", e.Name))
		b.WriteString(fmt.Sprintf("            values().firstOrNull { it.value == v }\n"))
		b.WriteString(fmt.Sprintf("                ?: error(\"Unknown %s value: $v\")\n", e.Name))
		b.WriteString("    }\n")
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, srcRoot, "models", "Enums.kt")
	return writeFile(path, b.String())
}

// ── Inputs ────────────────────────────────────────────────────────────────────

func writeInputs(schema *parser.Schema, outDir string) error {
	if len(schema.Inputs) == 0 {
		return nil
	}

	inputs := make([]*parser.InputType, len(schema.Inputs))
	copy(inputs, schema.Inputs)
	sort.Slice(inputs, func(i, j int) bool { return inputs[i].Name < inputs[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate kotlin\n\n")
	b.WriteString("package com.masterfabric.api.models\n\n")

	// Collect imports
	needsInstant := false
	for _, inp := range inputs {
		for _, f := range inp.Fields {
			if f.TypeName == "Time" {
				needsInstant = true
			}
		}
	}
	if needsInstant {
		b.WriteString("import java.time.Instant\n\n")
	}

	for _, inp := range inputs {
		b.WriteString(fmt.Sprintf("/** GraphQL input: %s */\n", inp.Name))
		b.WriteString(fmt.Sprintf("data class %s(\n", inp.Name))
		for i, f := range inp.Fields {
			ktType := fieldKotlinType(f)
			defaultVal := ""
			if !f.NonNull {
				defaultVal = " = null"
			}
			comma := ","
			if i == len(inp.Fields)-1 {
				comma = ""
			}
			b.WriteString(fmt.Sprintf("    val %s: %s%s%s\n", toCamelCase(f.Name), ktType, defaultVal, comma))
		}
		b.WriteString(") {\n")

		// toVariables(): Map<String, Any?>
		b.WriteString("    /** Converts to a variable map for the GraphQL request. */\n")
		b.WriteString("    fun toVariables(): Map<String, Any?> = buildMap {\n")
		for _, f := range inp.Fields {
			name := toCamelCase(f.Name)
			if isEnum(f.TypeName, schema) {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("        put(%q, %s.value)\n", f.Name, name))
				} else {
					b.WriteString(fmt.Sprintf("        %s?.let { put(%q, it.value) }\n", name, f.Name))
				}
			} else if f.TypeName == "Time" {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("        put(%q, %s.toString())\n", f.Name, name))
				} else {
					b.WriteString(fmt.Sprintf("        %s?.let { put(%q, it.toString()) }\n", name, f.Name))
				}
			} else {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("        put(%q, %s)\n", f.Name, name))
				} else {
					b.WriteString(fmt.Sprintf("        %s?.let { put(%q, it) }\n", name, f.Name))
				}
			}
		}
		b.WriteString("    }\n")
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, srcRoot, "models", "Inputs.kt")
	return writeFile(path, b.String())
}

// ── Models ────────────────────────────────────────────────────────────────────

func writeModels(schema *parser.Schema, outDir string) error {
	objects := make([]*parser.ObjectType, len(schema.Objects))
	copy(objects, schema.Objects)
	sort.Slice(objects, func(i, j int) bool { return objects[i].Name < objects[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate kotlin\n\n")
	b.WriteString("package com.masterfabric.api.models\n\n")

	// Check if any model needs Instant
	needsInstant := false
	for _, obj := range objects {
		for _, f := range obj.Fields {
			if f.TypeName == "Time" {
				needsInstant = true
			}
		}
	}
	if needsInstant {
		b.WriteString("import java.time.Instant\n")
	}
	b.WriteString("import com.google.gson.annotations.SerializedName\n\n")

	for _, obj := range objects {
		b.WriteString(fmt.Sprintf("/** GraphQL type: %s */\n", obj.Name))
		b.WriteString(fmt.Sprintf("data class %s(\n", obj.Name))
		for i, f := range obj.Fields {
			ktType := fieldKotlinType(f)
			defaultVal := ""
			if !f.NonNull {
				defaultVal = " = null"
			}
			comma := ","
			if i == len(obj.Fields)-1 {
				comma = ""
			}
			b.WriteString(fmt.Sprintf("    @SerializedName(%q)\n", f.Name))
			b.WriteString(fmt.Sprintf("    val %s: %s%s%s\n", toCamelCase(f.Name), ktType, defaultVal, comma))
		}
		b.WriteString(")\n\n")
	}

	path := filepath.Join(outDir, srcRoot, "models", "Models.kt")
	return writeFile(path, b.String())
}
