// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AdminUserList struct {
	Users      []*AdminUserProfile `json:"users"`
	TotalCount int                 `json:"totalCount"`
	Page       int                 `json:"page"`
	PageSize   int                 `json:"pageSize"`
}

type AdminUserProfile struct {
	ID             uuid.UUID  `json:"id"`
	Email          string     `json:"email"`
	DisplayName    string     `json:"displayName"`
	AvatarURL      string     `json:"avatarURL"`
	Bio            string     `json:"bio"`
	Status         UserStatus `json:"status"`
	Role           UserRole   `json:"role"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
	PhoneNumber    string     `json:"phoneNumber"`
	DateOfBirth    *string    `json:"dateOfBirth,omitempty"`
	Gender         Gender     `json:"gender"`
	Location       string     `json:"location"`
	WebsiteURL     string     `json:"websiteURL"`
	SocialTwitter  string     `json:"socialTwitter"`
	SocialGitHub   string     `json:"socialGitHub"`
	SocialLinkedIn string     `json:"socialLinkedIn"`
	Language       string     `json:"language"`
}

type AppSetting struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
}

type AuthPayload struct {
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
	ExpiresIn    int       `json:"expiresIn"`
	User         *AuthUser `json:"user"`
}

type AuthUser struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	AvatarURL   string    `json:"avatarURL"`
	Role        UserRole  `json:"role"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LogoutInput struct {
	UserID       uuid.UUID `json:"userID"`
	AccessToken  string    `json:"accessToken"`
	RefreshToken string    `json:"refreshToken"`
}

type Mutation struct {
}

type Query struct {
}

type RefreshInput struct {
	UserID       uuid.UUID `json:"userID"`
	RefreshToken string    `json:"refreshToken"`
}

type RegisterInput struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"displayName"`
}

type UpdateProfileInput struct {
	DisplayName    *string `json:"displayName,omitempty"`
	AvatarURL      *string `json:"avatarURL,omitempty"`
	Bio            *string `json:"bio,omitempty"`
	PhoneNumber    *string `json:"phoneNumber,omitempty"`
	DateOfBirth    *string `json:"dateOfBirth,omitempty"`
	Gender         *Gender `json:"gender,omitempty"`
	Location       *string `json:"location,omitempty"`
	WebsiteURL     *string `json:"websiteURL,omitempty"`
	SocialTwitter  *string `json:"socialTwitter,omitempty"`
	SocialGitHub   *string `json:"socialGitHub,omitempty"`
	SocialLinkedIn *string `json:"socialLinkedIn,omitempty"`
	Language       *string `json:"language,omitempty"`
}

type UpsertAddressInput struct {
	AddressID    *uuid.UUID `json:"addressID,omitempty"`
	Title        *string    `json:"title,omitempty"`
	AddressLine1 *string    `json:"addressLine1,omitempty"`
	AddressLine2 *string    `json:"addressLine2,omitempty"`
	City         *string    `json:"city,omitempty"`
	State        *string    `json:"state,omitempty"`
	PostalCode   *string    `json:"postalCode,omitempty"`
	Country      *string    `json:"country,omitempty"`
	IsDefault    *bool      `json:"isDefault,omitempty"`
}

type UserAddress struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"userID"`
	Title        string    `json:"title"`
	AddressLine1 string    `json:"addressLine1"`
	AddressLine2 string    `json:"addressLine2"`
	City         string    `json:"city"`
	State        string    `json:"state"`
	PostalCode   string    `json:"postalCode"`
	Country      string    `json:"country"`
	IsDefault    bool      `json:"isDefault"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type UserProfile struct {
	ID             uuid.UUID  `json:"id"`
	Email          string     `json:"email"`
	DisplayName    string     `json:"displayName"`
	AvatarURL      string     `json:"avatarURL"`
	Bio            string     `json:"bio"`
	Status         UserStatus `json:"status"`
	Role           UserRole   `json:"role"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
	PhoneNumber    string     `json:"phoneNumber"`
	DateOfBirth    *string    `json:"dateOfBirth,omitempty"`
	Gender         Gender     `json:"gender"`
	Location       string     `json:"location"`
	WebsiteURL     string     `json:"websiteURL"`
	SocialTwitter  string     `json:"socialTwitter"`
	SocialGitHub   string     `json:"socialGitHub"`
	SocialLinkedIn string     `json:"socialLinkedIn"`
	Language       string     `json:"language"`
	// The user's default address, if one has been set.
	Address *UserAddress `json:"address,omitempty"`
}

type UserSettingsInput struct {
	NotificationsOn *bool   `json:"notificationsOn,omitempty"`
	Theme           *Theme  `json:"theme,omitempty"`
	Language        *string `json:"language,omitempty"`
	Timezone        *string `json:"timezone,omitempty"`
}

type UserSettingsPayload struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"userID"`
	NotificationsOn bool      `json:"notificationsOn"`
	Theme           Theme     `json:"theme"`
	Language        string    `json:"language"`
	Timezone        string    `json:"timezone"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type Gender string

const (
	GenderMale           Gender = "MALE"
	GenderFemale         Gender = "FEMALE"
	GenderOther          Gender = "OTHER"
	GenderPreferNotToSay Gender = "PREFER_NOT_TO_SAY"
	GenderUnspecified    Gender = "UNSPECIFIED"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
	GenderOther,
	GenderPreferNotToSay,
	GenderUnspecified,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale, GenderOther, GenderPreferNotToSay, GenderUnspecified:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Theme string

const (
	ThemeLight  Theme = "LIGHT"
	ThemeDark   Theme = "DARK"
	ThemeSystem Theme = "SYSTEM"
)

var AllTheme = []Theme{
	ThemeLight,
	ThemeDark,
	ThemeSystem,
}

func (e Theme) IsValid() bool {
	switch e {
	case ThemeLight, ThemeDark, ThemeSystem:
		return true
	}
	return false
}

func (e Theme) String() string {
	return string(e)
}

func (e *Theme) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Theme(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Theme", str)
	}
	return nil
}

func (e Theme) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserRole string

const (
	UserRoleAdmin     UserRole = "ADMIN"
	UserRoleModerator UserRole = "MODERATOR"
	UserRoleUser      UserRole = "USER"
)

var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleModerator,
	UserRoleUser,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleAdmin, UserRoleModerator, UserRoleUser:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
