package swift

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writeClient generates Sources/MasterFabricAPI/Client/MasterFabricClient.swift —
// a typed async/await Swift client that sends GraphQL requests over URLSession.
// It does NOT depend on Apollo at runtime — it is a plain URLSession HTTP client
// that serialises/deserialises JSON manually, making it usable in any iOS/macOS
// app without any additional SPM dependency on the call site.
func writeClient(schema *parser.Schema, outDir string) error {
	var b strings.Builder

	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate swift\n\n")
	b.WriteString("import Foundation\n\n")

	// ── Error type ────────────────────────────────────────────────────────────
	b.WriteString(`/// A single error returned by the GraphQL server.
public struct GraphQLErrorResponse: Decodable {
    public let message: String
    public let locations: [[String: Int]]?
    public let path: [String]?
}

/// Thrown when the server returns a non-null errors array.
public struct MasterFabricError: Error, CustomStringConvertible {
    public let errors: [GraphQLErrorResponse]

    public var description: String {
        errors.map(\.message).joined(separator: "; ")
    }
}

/// Thrown when the server returns no data and no errors (should not happen).
public struct MasterFabricEmptyDataError: Error {}

`)

	// ── Private response envelope ─────────────────────────────────────────────
	b.WriteString(`// MARK: — Internal response envelope

private struct GraphQLResponse<T: Decodable>: Decodable {
    let data: T?
    let errors: [GraphQLErrorResponse]?
}

`)

	// ── Client class ──────────────────────────────────────────────────────────
	b.WriteString("/// Typed async/await GraphQL client for the MasterFabric API.\n")
	b.WriteString("///\n")
	b.WriteString("/// Instantiate once and share across your app (e.g. via @EnvironmentObject / DI).\n")
	b.WriteString("///\n")
	b.WriteString("/// Example:\n")
	b.WriteString("/// ```swift\n")
	b.WriteString("/// let client = MasterFabricClient(endpoint: URL(string: \"http://localhost:8080/graphql\")!)\n")
	b.WriteString("/// let payload = try await client.register(input: RegisterInput(\n")
	b.WriteString("///     email: \"user@example.com\", password: \"secret\", displayName: \"Alice\"\n")
	b.WriteString("/// ))\n")
	b.WriteString("/// ```\n")
	b.WriteString("public final class MasterFabricClient {\n\n")
	b.WriteString("    private let endpoint: URL\n")
	b.WriteString("    private var authToken: String?\n")
	b.WriteString("    private let session: URLSession\n\n")

	b.WriteString("    public init(\n")
	b.WriteString("        endpoint: URL,\n")
	b.WriteString("        authToken: String? = nil,\n")
	b.WriteString("        session: URLSession = .shared\n")
	b.WriteString("    ) {\n")
	b.WriteString("        self.endpoint = endpoint\n")
	b.WriteString("        self.authToken = authToken\n")
	b.WriteString("        self.session = session\n")
	b.WriteString("    }\n\n")

	b.WriteString("    /// Returns a new client with the given auth token (e.g. after login / token refresh).\n")
	b.WriteString("    public func withToken(_ token: String) -> MasterFabricClient {\n")
	b.WriteString("        MasterFabricClient(endpoint: endpoint, authToken: token, session: session)\n")
	b.WriteString("    }\n\n")

	// ── Generated query/mutation methods ──────────────────────────────────────
	for _, q := range schema.Queries {
		if isIntrospectionField(q.Name) {
			continue
		}
		b.WriteString(buildSwiftQueryMethod(q, schema))
		b.WriteString("\n")
	}
	for _, m := range schema.Mutations {
		if isIntrospectionField(m.Name) {
			continue
		}
		b.WriteString(buildSwiftMutationMethod(m, schema))
		b.WriteString("\n")
	}

	// ── Private execute helper ─────────────────────────────────────────────────
	b.WriteString("    // MARK: — Private helpers\n\n")
	b.WriteString(buildExecuteHelper())

	b.WriteString("}\n")

	path := filepath.Join(outDir, "Sources", "MasterFabricAPI", "Client", "MasterFabricClient.swift")
	return writeFile(path, b.String())
}

// ── Method builders ───────────────────────────────────────────────────────────

func buildSwiftQueryMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnSwift := swiftReturnType(op, schema)
	params := buildSwiftParams(op.Args, schema)
	constName := toSwiftConstName(op.Name) + "Query"
	dataKey := op.Name

	b.WriteString(fmt.Sprintf("    /// Query: %s\n", op.Name))
	if params == "" {
		b.WriteString(fmt.Sprintf("    public func %s() async throws -> %s {\n", toCamelCase(op.Name), returnSwift))
	} else {
		b.WriteString(fmt.Sprintf("    public func %s(\n%s\n    ) async throws -> %s {\n", toCamelCase(op.Name), params, returnSwift))
	}
	b.WriteString(fmt.Sprintf("        let query = MasterFabricDocuments.%s\n", constName))
	b.WriteString(buildVariablesBlock(op.Args))
	b.WriteString(fmt.Sprintf("        return try await execute(query: query, variables: variables, dataKey: %q, as: %s.self)\n", dataKey, swiftDecodeType(op, schema)))
	b.WriteString("    }\n")
	return b.String()
}

func buildSwiftMutationMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnSwift := swiftReturnType(op, schema)
	params := buildSwiftParams(op.Args, schema)
	constName := toSwiftConstName(op.Name) + "Mutation"
	dataKey := op.Name

	b.WriteString(fmt.Sprintf("    /// Mutation: %s\n", op.Name))
	if params == "" {
		b.WriteString(fmt.Sprintf("    public func %s() async throws -> %s {\n", toCamelCase(op.Name), returnSwift))
	} else {
		b.WriteString(fmt.Sprintf("    public func %s(\n%s\n    ) async throws -> %s {\n", toCamelCase(op.Name), params, returnSwift))
	}
	b.WriteString(fmt.Sprintf("        let query = MasterFabricDocuments.%s\n", constName))
	b.WriteString(buildVariablesBlock(op.Args))
	b.WriteString(fmt.Sprintf("        return try await execute(query: query, variables: variables, dataKey: %q, as: %s.self)\n", dataKey, swiftDecodeType(op, schema)))
	b.WriteString("    }\n")
	return b.String()
}

// swiftReturnType returns the Swift return type for async throws -> T.
func swiftReturnType(op *parser.Operation, schema *parser.Schema) string {
	if op.ReturnType == "" || op.ReturnType == "Boolean" {
		if op.ReturnNull {
			return "Bool?"
		}
		return "Bool"
	}
	if isScalar(op.ReturnType) {
		base := gqlToSwiftBase(op.ReturnType)
		if op.ReturnList {
			return fmt.Sprintf("[%s]", base)
		}
		if op.ReturnNull {
			return base + "?"
		}
		return base
	}
	base := op.ReturnType
	if op.ReturnList {
		return fmt.Sprintf("[%s]", base)
	}
	if op.ReturnNull {
		return base + "?"
	}
	return base
}

// swiftDecodeType returns the type to pass to JSONDecoder for the given operation.
// For lists we wrap in an array type, for scalars we use the primitive.
func swiftDecodeType(op *parser.Operation, schema *parser.Schema) string {
	if op.ReturnType == "" || op.ReturnType == "Boolean" {
		return "Bool"
	}
	if isScalar(op.ReturnType) {
		return gqlToSwiftBase(op.ReturnType)
	}
	if op.ReturnList {
		return fmt.Sprintf("[%s]", op.ReturnType)
	}
	return op.ReturnType
}

// buildSwiftParams builds the Swift function parameter list (multi-line).
func buildSwiftParams(args []*parser.Argument, schema *parser.Schema) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		swiftType := argSwiftType(a, schema)
		parts = append(parts, fmt.Sprintf("        %s: %s", toCamelCase(a.Name), swiftType))
	}
	return strings.Join(parts, ",\n")
}

func argSwiftType(a *parser.Argument, schema *parser.Schema) string {
	if isScalar(a.TypeName) {
		return gqlToSwift(a.TypeName, a.NonNull)
	}
	if a.NonNull {
		return a.TypeName
	}
	return a.TypeName + "?"
}

// buildVariablesBlock emits the variables dictionary assignment.
func buildVariablesBlock(args []*parser.Argument) string {
	if len(args) == 0 {
		return "        let variables: [String: Any] = [:]\n"
	}
	var b strings.Builder
	b.WriteString("        var variables: [String: Any] = [:]\n")
	for _, a := range args {
		name := toCamelCase(a.Name)
		if isScalar(a.TypeName) {
			b.WriteString(fmt.Sprintf("        variables[%q] = %s\n", a.Name, name))
		} else {
			// Input type — call toVariables()
			b.WriteString(fmt.Sprintf("        variables[%q] = %s.toVariables()\n", a.Name, name))
		}
	}
	return b.String()
}

// buildExecuteHelper emits the private _execute generic method.
func buildExecuteHelper() string {
	return `    private func execute<T: Decodable>(
        query: String,
        variables: [String: Any],
        dataKey: String,
        as type: T.Type
    ) async throws -> T {
        var request = URLRequest(url: endpoint)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        if let token = authToken {
            request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        }

        let body: [String: Any] = ["query": query, "variables": variables]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, _) = try await session.data(for: request)

        // Check for GraphQL-level errors first
        if let raw = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let errorsArray = raw["errors"] as? [[String: Any]], !errorsArray.isEmpty {
            let errData = try JSONSerialization.data(withJSONObject: ["errors": errorsArray])
            struct ErrEnvelope: Decodable { let errors: [GraphQLErrorResponse] }
            let envelope = try JSONDecoder().decode(ErrEnvelope.self, from: errData)
            throw MasterFabricError(errors: envelope.errors)
        }

        // Decode the data field
        guard let raw = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let dataObject = raw["data"] as? [String: Any],
              let field = dataObject[dataKey] else {
            throw MasterFabricEmptyDataError()
        }

        let fieldData = try JSONSerialization.data(withJSONObject: field)
        let decoder = JSONDecoder()
        return try decoder.decode(T.self, from: fieldData)
    }

`
}
