package swift

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// ── Type mapping ─────────────────────────────────────────────────────────────

// gqlToSwift converts a GraphQL type name to a Swift type.
func gqlToSwift(typeName string, nonNull bool) string {
	base := gqlToSwiftBase(typeName)
	if !nonNull {
		return base + "?"
	}
	return base
}

func gqlToSwiftBase(typeName string) string {
	switch typeName {
	case "String", "UUID", "ID":
		return "String"
	case "Int":
		return "Int"
	case "Float":
		return "Double"
	case "Boolean":
		return "Bool"
	case "Time":
		return "Date"
	default:
		return typeName
	}
}

// isScalar returns true for types that map directly to Swift primitives.
func isScalar(typeName string) bool {
	switch typeName {
	case "String", "UUID", "ID", "Int", "Float", "Boolean", "Time":
		return true
	}
	return false
}

// screamingToCamel converts SCREAMING_SNAKE_CASE → lowerCamelCase for Swift enum cases.
func screamingToCamel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	if len(parts) == 1 {
		return parts[0]
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(p)
		} else {
			if len(p) > 0 {
				b.WriteString(strings.ToUpper(p[:1]) + p[1:])
			}
		}
	}
	return b.String()
}

// toCamelCase lower-cases the first letter.
func toCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// isEnum returns true if typeName is an enum in the schema.
func isEnum(typeName string, schema *parser.Schema) bool {
	for _, e := range schema.Enums {
		if e.Name == typeName {
			return true
		}
	}
	return false
}

// isObject returns true if typeName is an object type in the schema.
func isObject(typeName string, schema *parser.Schema) bool {
	for _, o := range schema.Objects {
		if o.Name == typeName {
			return true
		}
	}
	return false
}

// isInput returns true if typeName is an input type in the schema.
func isInput(typeName string, schema *parser.Schema) bool {
	for _, i := range schema.Inputs {
		if i.Name == typeName {
			return true
		}
	}
	return false
}

// isIntrospectionField returns true for built-in GraphQL introspection fields.
func isIntrospectionField(name string) bool {
	return len(name) > 1 && name[:2] == "__"
}

// fieldSwiftType returns the full Swift type string for a field.
func fieldSwiftType(f *parser.Field) string {
	if f.IsList {
		inner := gqlToSwiftBase(f.TypeName)
		if f.NonNull {
			return fmt.Sprintf("[%s]", inner)
		}
		return fmt.Sprintf("[%s]?", inner)
	}
	return gqlToSwift(f.TypeName, f.NonNull)
}

// ── Package manifest ──────────────────────────────────────────────────────────

func writePackageManifest(_ *parser.Schema, outDir string) error {
	content := `// GENERATED CODE — DO NOT EDIT BY HAND
// Generated by masterfabric_go generate swift
// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "MasterFabricAPI",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(
            name: "MasterFabricAPI",
            targets: ["MasterFabricAPI"]
        ),
    ],
    dependencies: [
        // Apollo iOS for GraphQL networking
        .package(
            url: "https://github.com/apollographql/apollo-ios",
            from: "1.9.0"
        ),
    ],
    targets: [
        .target(
            name: "MasterFabricAPI",
            dependencies: [
                .product(name: "Apollo", package: "apollo-ios"),
                .product(name: "ApolloAPI", package: "apollo-ios"),
            ]
        ),
    ]
)
`
	path := filepath.Join(outDir, "Package.swift")
	return writeFile(path, content)
}

// ── Enums ─────────────────────────────────────────────────────────────────────

func writeEnums(schema *parser.Schema, outDir string) error {
	if len(schema.Enums) == 0 {
		return nil
	}

	enums := make([]*parser.EnumType, len(schema.Enums))
	copy(enums, schema.Enums)
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate swift\n\n")
	b.WriteString("import Foundation\n\n")

	for _, e := range enums {
		b.WriteString(fmt.Sprintf("/// GraphQL enum: %s\n", e.Name))
		b.WriteString(fmt.Sprintf("public enum %s: String, Codable, CaseIterable {\n", e.Name))
		for _, v := range e.Values {
			dartVal := screamingToCamel(v)
			b.WriteString(fmt.Sprintf("    case %s = %q\n", dartVal, v))
		}
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "Sources", "MasterFabricAPI", "Models", "Enums.swift")
	return writeFile(path, b.String())
}

// ── Inputs ────────────────────────────────────────────────────────────────────

func writeInputs(schema *parser.Schema, outDir string) error {
	if len(schema.Inputs) == 0 {
		return nil
	}

	inputs := make([]*parser.InputType, len(schema.Inputs))
	copy(inputs, schema.Inputs)
	sort.Slice(inputs, func(i, j int) bool { return inputs[i].Name < inputs[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate swift\n\n")
	b.WriteString("import Foundation\n\n")

	for _, inp := range inputs {
		b.WriteString(fmt.Sprintf("/// GraphQL input: %s\n", inp.Name))
		b.WriteString(fmt.Sprintf("public struct %s: Encodable {\n", inp.Name))

		// Properties
		for _, f := range inp.Fields {
			swiftType := fieldSwiftType(f)
			b.WriteString(fmt.Sprintf("    public let %s: %s\n", toCamelCase(f.Name), swiftType))
		}
		b.WriteString("\n")

		// Memberwise init
		b.WriteString(fmt.Sprintf("    public init(\n"))
		for i, f := range inp.Fields {
			swiftType := fieldSwiftType(f)
			defaultVal := ""
			if !f.NonNull {
				defaultVal = " = nil"
			}
			comma := ","
			if i == len(inp.Fields)-1 {
				comma = ""
			}
			b.WriteString(fmt.Sprintf("        %s: %s%s%s\n", toCamelCase(f.Name), swiftType, defaultVal, comma))
		}
		b.WriteString("    ) {\n")
		for _, f := range inp.Fields {
			name := toCamelCase(f.Name)
			b.WriteString(fmt.Sprintf("        self.%s = %s\n", name, name))
		}
		b.WriteString("    }\n\n")

		// toVariables — converts to [String: Any?] for Apollo variables
		b.WriteString("    /// Converts to a [String: Any?] dictionary suitable for Apollo variables.\n")
		b.WriteString("    public func toVariables() -> [String: Any?] {\n")
		b.WriteString("        var dict: [String: Any?] = [:]\n")
		for _, f := range inp.Fields {
			name := toCamelCase(f.Name)
			if isEnum(f.TypeName, schema) {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("        dict[%q] = %s.rawValue\n", f.Name, name))
				} else {
					b.WriteString(fmt.Sprintf("        dict[%q] = %s?.rawValue\n", f.Name, name))
				}
			} else if f.TypeName == "Time" {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("        dict[%q] = ISO8601DateFormatter().string(from: %s)\n", f.Name, name))
				} else {
					b.WriteString(fmt.Sprintf("        if let v = %s { dict[%q] = ISO8601DateFormatter().string(from: v) }\n", name, f.Name))
				}
			} else {
				if f.NonNull {
					b.WriteString(fmt.Sprintf("        dict[%q] = %s\n", f.Name, name))
				} else {
					b.WriteString(fmt.Sprintf("        if let v = %s { dict[%q] = v }\n", name, f.Name))
				}
			}
		}
		b.WriteString("        return dict\n")
		b.WriteString("    }\n")
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "Sources", "MasterFabricAPI", "Models", "Inputs.swift")
	return writeFile(path, b.String())
}

// ── Models ────────────────────────────────────────────────────────────────────

func writeModels(schema *parser.Schema, outDir string) error {
	objects := make([]*parser.ObjectType, len(schema.Objects))
	copy(objects, schema.Objects)
	sort.Slice(objects, func(i, j int) bool { return objects[i].Name < objects[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate swift\n\n")
	b.WriteString("import Foundation\n\n")

	for _, obj := range objects {
		b.WriteString(fmt.Sprintf("/// GraphQL type: %s\n", obj.Name))
		b.WriteString(fmt.Sprintf("public struct %s: Decodable {\n", obj.Name))

		for _, f := range obj.Fields {
			swiftType := fieldSwiftType(f)
			b.WriteString(fmt.Sprintf("    public let %s: %s\n", toCamelCase(f.Name), swiftType))
		}
		b.WriteString("\n")

		// CodingKeys — only needed when field names require mapping
		// GraphQL field names are already camelCase so we can use default decoding;
		// but Time fields need a custom Date decoding strategy so we keep CodingKeys
		// explicit for clarity.
		b.WriteString("    enum CodingKeys: String, CodingKey {\n")
		for _, f := range obj.Fields {
			name := toCamelCase(f.Name)
			b.WriteString(fmt.Sprintf("        case %s = %q\n", name, f.Name))
		}
		b.WriteString("    }\n\n")

		// Custom init(from decoder) for Date and enum fields
		needsCustomDecoder := false
		for _, f := range obj.Fields {
			if f.TypeName == "Time" || isEnum(f.TypeName, schema) {
				needsCustomDecoder = true
				break
			}
		}

		if needsCustomDecoder {
			b.WriteString("    public init(from decoder: Decoder) throws {\n")
			b.WriteString("        let container = try decoder.container(keyedBy: CodingKeys.self)\n")
			for _, f := range obj.Fields {
				name := toCamelCase(f.Name)
				swiftType := fieldSwiftType(f)
				if f.TypeName == "Time" {
					if f.IsList {
						b.WriteString(fmt.Sprintf("        let %sStrings = try container.decode([String].self, forKey: .%s)\n", name, name))
						b.WriteString(fmt.Sprintf("        self.%s = %sStrings.compactMap { ISO8601DateFormatter().date(from: $0) }\n", name, name))
					} else if f.NonNull {
						b.WriteString(fmt.Sprintf("        let %sString = try container.decode(String.self, forKey: .%s)\n", name, name))
						b.WriteString(fmt.Sprintf("        guard let %sDate = ISO8601DateFormatter().date(from: %sString) else {\n", name, name))
						b.WriteString(fmt.Sprintf("            throw DecodingError.dataCorruptedError(forKey: .%s, in: container, debugDescription: \"Invalid ISO8601 date\")\n", name))
						b.WriteString("        }\n")
						b.WriteString(fmt.Sprintf("        self.%s = %sDate\n", name, name))
					} else {
						b.WriteString(fmt.Sprintf("        if let %sString = try container.decodeIfPresent(String.self, forKey: .%s) {\n", name, name))
						b.WriteString(fmt.Sprintf("            self.%s = ISO8601DateFormatter().date(from: %sString)\n", name, name))
						b.WriteString("        } else {\n")
						b.WriteString(fmt.Sprintf("            self.%s = nil\n", name))
						b.WriteString("        }\n")
					}
				} else if isEnum(f.TypeName, schema) {
					if f.NonNull {
						b.WriteString(fmt.Sprintf("        let %sRaw = try container.decode(String.self, forKey: .%s)\n", name, name))
						b.WriteString(fmt.Sprintf("        guard let %sVal = %s(rawValue: %sRaw) else {\n", name, f.TypeName, name))
						b.WriteString(fmt.Sprintf("            throw DecodingError.dataCorruptedError(forKey: .%s, in: container, debugDescription: \"Unknown %s: \\(%sRaw)\")\n", name, f.TypeName, name))
						b.WriteString("        }\n")
						b.WriteString(fmt.Sprintf("        self.%s = %sVal\n", name, name))
					} else {
						b.WriteString(fmt.Sprintf("        if let %sRaw = try container.decodeIfPresent(String.self, forKey: .%s) {\n", name, name))
						b.WriteString(fmt.Sprintf("            self.%s = %s(rawValue: %sRaw)\n", name, f.TypeName, name))
						b.WriteString("        } else {\n")
						b.WriteString(fmt.Sprintf("            self.%s = nil\n", name))
						b.WriteString("        }\n")
					}
				} else {
					if f.NonNull {
						b.WriteString(fmt.Sprintf("        self.%s = try container.decode(%s.self, forKey: .%s)\n", name, swiftType, name))
					} else {
						b.WriteString(fmt.Sprintf("        self.%s = try container.decodeIfPresent(%s.self, forKey: .%s)\n", name, strings.TrimSuffix(swiftType, "?"), name))
					}
				}
			}
			b.WriteString("    }\n")
		}

		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "Sources", "MasterFabricAPI", "Models", "Models.swift")
	return writeFile(path, b.String())
}
