package typescript

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writeClient generates src/client/MasterFabricClient.ts — a typed
// async/await client using the native fetch API (Node 18+ / browsers).
func writeClient(schema *parser.Schema, outDir string) error {
	var b strings.Builder

	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate typescript\n\n")
	b.WriteString("import type { ")

	// Collect all model types needed
	modelTypes := collectModelTypes(schema)
	inputTypes := collectInputTypes(schema)
	allTypes := append(modelTypes, inputTypes...)
	if len(allTypes) > 0 {
		b.WriteString(strings.Join(allTypes, ", "))
	}
	b.WriteString(" } from '../models/models';\n")
	b.WriteString("import { MasterFabricDocuments } from '../queries/documents';\n\n")

	// Error types
	b.WriteString(`/** A single GraphQL error returned by the server. */
export interface GraphQLErrorDetail {
  message: string;
  locations?: Array<{ line: number; column: number }>;
  path?: string[];
}

/** Thrown when the server returns a non-empty errors array. */
export class MasterFabricException extends Error {
  constructor(public readonly errors: GraphQLErrorDetail[]) {
    super(errors.map((e) => e.message).join('; '));
    this.name = 'MasterFabricException';
  }
}

`)

	// Client class
	b.WriteString("/**\n")
	b.WriteString(" * Typed async/await GraphQL client for the MasterFabric API.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Uses the native fetch API (Node 18+ / any modern browser).\n")
	b.WriteString(" *\n")
	b.WriteString(" * Example:\n")
	b.WriteString(" * ```typescript\n")
	b.WriteString(" * const client = new MasterFabricClient({ endpoint: 'http://localhost:8080/graphql' });\n")
	b.WriteString(" * const payload = await client.register({\n")
	b.WriteString(" *   input: { email: 'user@example.com', password: 'secret', displayName: 'Alice' },\n")
	b.WriteString(" * });\n")
	b.WriteString(" * ```\n")
	b.WriteString(" */\n")
	b.WriteString("export class MasterFabricClient {\n")
	b.WriteString("  private readonly endpoint: string;\n")
	b.WriteString("  private authToken?: string;\n\n")

	b.WriteString("  constructor(options: { endpoint: string; authToken?: string }) {\n")
	b.WriteString("    this.endpoint = options.endpoint;\n")
	b.WriteString("    this.authToken = options.authToken;\n")
	b.WriteString("  }\n\n")

	b.WriteString("  /** Returns a new client with the given auth token (e.g. after login / token refresh). */\n")
	b.WriteString("  withToken(token: string): MasterFabricClient {\n")
	b.WriteString("    return new MasterFabricClient({ endpoint: this.endpoint, authToken: token });\n")
	b.WriteString("  }\n\n")

	// Generate query methods
	for _, q := range schema.Queries {
		if isIntrospectionField(q.Name) {
			continue
		}
		b.WriteString(buildTSQueryMethod(q, schema))
		b.WriteString("\n")
	}

	// Generate mutation methods
	for _, m := range schema.Mutations {
		if isIntrospectionField(m.Name) {
			continue
		}
		b.WriteString(buildTSMutationMethod(m, schema))
		b.WriteString("\n")
	}

	// Private execute helper
	b.WriteString("  // ── Private helpers ──────────────────────────────────────────────────\n\n")
	b.WriteString(buildTSExecuteHelper())

	b.WriteString("}\n")

	path := filepath.Join(outDir, "src", "client", "MasterFabricClient.ts")
	return writeFile(path, b.String())
}

// collectModelTypes returns a sorted list of all object type names referenced
// by operations (for the import statement).
func collectModelTypes(schema *parser.Schema) []string {
	seen := map[string]bool{}
	allOps := append(schema.Queries, schema.Mutations...)
	for _, op := range allOps {
		if op.ReturnType != "" && !isScalar(op.ReturnType) && op.ReturnType != "Boolean" {
			seen[op.ReturnType] = true
		}
	}
	result := make([]string, 0, len(seen))
	for k := range seen {
		result = append(result, k)
	}
	return result
}

// collectInputTypes returns a sorted list of all input type names referenced
// by operations (for the import statement).
func collectInputTypes(schema *parser.Schema) []string {
	seen := map[string]bool{}
	allOps := append(schema.Queries, schema.Mutations...)
	for _, op := range allOps {
		for _, a := range op.Args {
			if isInput(a.TypeName, schema) {
				seen[a.TypeName] = true
			}
		}
	}
	result := make([]string, 0, len(seen))
	for k := range seen {
		result = append(result, k)
	}
	return result
}

// ── Method builders ───────────────────────────────────────────────────────────

func buildTSQueryMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnTS := tsReturnType(op, schema)
	paramsType := buildTSParamsType(op.Args, schema)
	constName := toCamelCase(op.Name) + "Query"

	b.WriteString(fmt.Sprintf("  /** Query: %s */\n", op.Name))
	if paramsType == "" {
		b.WriteString(fmt.Sprintf("  async %s(): Promise<%s> {\n", toCamelCase(op.Name), returnTS))
	} else {
		b.WriteString(fmt.Sprintf("  async %s(args: %s): Promise<%s> {\n", toCamelCase(op.Name), paramsType, returnTS))
	}
	b.WriteString(fmt.Sprintf("    const query = MasterFabricDocuments.%s;\n", constName))
	b.WriteString(buildTSVariablesBlock(op.Args, schema))
	b.WriteString(fmt.Sprintf("    return this.execute<%s>(query, variables, %q);\n", returnTS, op.Name))
	b.WriteString("  }\n")
	return b.String()
}

func buildTSMutationMethod(op *parser.Operation, schema *parser.Schema) string {
	var b strings.Builder
	returnTS := tsReturnType(op, schema)
	paramsType := buildTSParamsType(op.Args, schema)
	constName := toCamelCase(op.Name) + "Mutation"

	b.WriteString(fmt.Sprintf("  /** Mutation: %s */\n", op.Name))
	if paramsType == "" {
		b.WriteString(fmt.Sprintf("  async %s(): Promise<%s> {\n", toCamelCase(op.Name), returnTS))
	} else {
		b.WriteString(fmt.Sprintf("  async %s(args: %s): Promise<%s> {\n", toCamelCase(op.Name), paramsType, returnTS))
	}
	b.WriteString(fmt.Sprintf("    const query = MasterFabricDocuments.%s;\n", constName))
	b.WriteString(buildTSVariablesBlock(op.Args, schema))
	b.WriteString(fmt.Sprintf("    return this.execute<%s>(query, variables, %q);\n", returnTS, op.Name))
	b.WriteString("  }\n")
	return b.String()
}

// tsReturnType returns the TypeScript return type for Promise<T>.
func tsReturnType(op *parser.Operation, schema *parser.Schema) string {
	if op.ReturnType == "" || op.ReturnType == "Boolean" {
		if op.ReturnNull {
			return "boolean | null"
		}
		return "boolean"
	}
	if isScalar(op.ReturnType) {
		base := gqlToTSBase(op.ReturnType)
		if op.ReturnList {
			return fmt.Sprintf("%s[]", base)
		}
		if op.ReturnNull {
			return base + " | null"
		}
		return base
	}
	base := op.ReturnType
	if op.ReturnList {
		return fmt.Sprintf("%s[]", base)
	}
	if op.ReturnNull {
		return base + " | null"
	}
	return base
}

// buildTSParamsType builds an inline object type for the method args.
func buildTSParamsType(args []*parser.Argument, schema *parser.Schema) string {
	if len(args) == 0 {
		return ""
	}
	var parts []string
	for _, a := range args {
		tsType := argTSType(a, schema)
		optional := ""
		if !a.NonNull {
			optional = "?"
		}
		parts = append(parts, fmt.Sprintf("%s%s: %s", toCamelCase(a.Name), optional, tsType))
	}
	return "{ " + strings.Join(parts, "; ") + " }"
}

func argTSType(a *parser.Argument, schema *parser.Schema) string {
	if isScalar(a.TypeName) {
		return gqlToTS(a.TypeName, a.NonNull)
	}
	if a.NonNull {
		return a.TypeName
	}
	return a.TypeName + " | null"
}

// buildTSVariablesBlock emits the variables object literal for the request.
func buildTSVariablesBlock(args []*parser.Argument, schema *parser.Schema) string {
	if len(args) == 0 {
		return "    const variables: Record<string, unknown> = {};\n"
	}
	var b strings.Builder
	b.WriteString("    const variables: Record<string, unknown> = {\n")
	for _, a := range args {
		name := toCamelCase(a.Name)
		b.WriteString(fmt.Sprintf("      %s: args.%s,\n", a.Name, name))
	}
	b.WriteString("    };\n")
	return b.String()
}

// buildTSExecuteHelper emits the private generic execute method.
func buildTSExecuteHelper() string {
	return `  private async execute<T>(
    query: string,
    variables: Record<string, unknown>,
    dataKey: string
  ): Promise<T> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (this.authToken) {
      headers['Authorization'] = ` + "`Bearer ${this.authToken}`" + `;
    }

    const response = await fetch(this.endpoint, {
      method: 'POST',
      headers,
      body: JSON.stringify({ query, variables }),
    });

    const json = await response.json() as {
      data?: Record<string, unknown>;
      errors?: GraphQLErrorDetail[];
    };

    if (json.errors && json.errors.length > 0) {
      throw new MasterFabricException(json.errors);
    }

    if (!json.data || !(dataKey in json.data)) {
      throw new Error(` + "`Missing field '${dataKey}' in response data`" + `);
    }

    return json.data[dataKey] as T;
  }

`
}
