package typescript

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// ── Type mapping ──────────────────────────────────────────────────────────────

// gqlToTS converts a GraphQL type name to a TypeScript type.
func gqlToTS(typeName string, nonNull bool) string {
	base := gqlToTSBase(typeName)
	if !nonNull {
		return base + " | null"
	}
	return base
}

func gqlToTSBase(typeName string) string {
	switch typeName {
	case "String", "UUID", "ID":
		return "string"
	case "Int", "Float":
		return "number"
	case "Boolean":
		return "boolean"
	case "Time":
		return "string" // ISO-8601 string; callers can parse with new Date()
	default:
		return typeName
	}
}

// isScalar returns true for GraphQL built-in scalars.
func isScalar(typeName string) bool {
	switch typeName {
	case "String", "UUID", "ID", "Int", "Float", "Boolean", "Time":
		return true
	}
	return false
}

// isEnum returns true if typeName is an enum in the schema.
func isEnum(typeName string, schema *parser.Schema) bool {
	for _, e := range schema.Enums {
		if e.Name == typeName {
			return true
		}
	}
	return false
}

// isObject returns true if typeName is an object type in the schema.
func isObject(typeName string, schema *parser.Schema) bool {
	for _, o := range schema.Objects {
		if o.Name == typeName {
			return true
		}
	}
	return false
}

// isInput returns true if typeName is an input type in the schema.
func isInput(typeName string, schema *parser.Schema) bool {
	for _, i := range schema.Inputs {
		if i.Name == typeName {
			return true
		}
	}
	return false
}

// isIntrospectionField returns true for __-prefixed fields.
func isIntrospectionField(name string) bool {
	return len(name) > 1 && name[:2] == "__"
}

// toCamelCase lower-cases the first letter.
func toCamelCase(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// screamingToCamel converts SCREAMING_SNAKE_CASE → lowerCamelCase.
func screamingToCamel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	if len(parts) == 1 {
		return parts[0]
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(p)
		} else {
			if len(p) > 0 {
				b.WriteString(strings.ToUpper(p[:1]) + p[1:])
			}
		}
	}
	return b.String()
}

// fieldTSType returns the TypeScript type string for a field.
func fieldTSType(f *parser.Field) string {
	if f.IsList {
		inner := gqlToTSBase(f.TypeName)
		if f.NonNull {
			return fmt.Sprintf("%s[]", inner)
		}
		return fmt.Sprintf("%s[] | null", inner)
	}
	return gqlToTS(f.TypeName, f.NonNull)
}

// ── Enums ─────────────────────────────────────────────────────────────────────

func writeEnums(schema *parser.Schema, outDir string) error {
	if len(schema.Enums) == 0 {
		return nil
	}

	enums := make([]*parser.EnumType, len(schema.Enums))
	copy(enums, schema.Enums)
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate typescript\n\n")

	for _, e := range enums {
		b.WriteString(fmt.Sprintf("/** GraphQL enum: %s */\n", e.Name))
		b.WriteString(fmt.Sprintf("export enum %s {\n", e.Name))
		for _, v := range e.Values {
			camelVal := screamingToCamel(v)
			entryName := strings.ToUpper(camelVal[:1]) + camelVal[1:]
			b.WriteString(fmt.Sprintf("  %s = %q,\n", entryName, v))
		}
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "src", "models", "enums.ts")
	return writeFile(path, b.String())
}

// ── Inputs ────────────────────────────────────────────────────────────────────

func writeInputs(schema *parser.Schema, outDir string) error {
	if len(schema.Inputs) == 0 {
		return nil
	}

	inputs := make([]*parser.InputType, len(schema.Inputs))
	copy(inputs, schema.Inputs)
	sort.Slice(inputs, func(i, j int) bool { return inputs[i].Name < inputs[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate typescript\n\n")

	// Check if any input uses enums
	needsEnumImport := false
	enumNames := map[string]bool{}
	for _, inp := range inputs {
		for _, f := range inp.Fields {
			if isEnum(f.TypeName, schema) {
				needsEnumImport = true
				enumNames[f.TypeName] = true
			}
		}
	}
	if needsEnumImport {
		names := make([]string, 0, len(enumNames))
		for n := range enumNames {
			names = append(names, n)
		}
		sort.Strings(names)
		b.WriteString(fmt.Sprintf("import { %s } from './enums';\n\n", strings.Join(names, ", ")))
	}

	for _, inp := range inputs {
		b.WriteString(fmt.Sprintf("/** GraphQL input: %s */\n", inp.Name))
		b.WriteString(fmt.Sprintf("export interface %s {\n", inp.Name))
		for _, f := range inp.Fields {
			tsType := fieldTSType(f)
			optional := ""
			if !f.NonNull {
				optional = "?"
			}
			b.WriteString(fmt.Sprintf("  %s%s: %s;\n", toCamelCase(f.Name), optional, tsType))
		}
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "src", "models", "inputs.ts")
	return writeFile(path, b.String())
}

// ── Models ────────────────────────────────────────────────────────────────────

func writeModels(schema *parser.Schema, outDir string) error {
	objects := make([]*parser.ObjectType, len(schema.Objects))
	copy(objects, schema.Objects)
	sort.Slice(objects, func(i, j int) bool { return objects[i].Name < objects[j].Name })

	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate typescript\n\n")

	// Collect enum imports needed
	enumNames := map[string]bool{}
	for _, obj := range objects {
		for _, f := range obj.Fields {
			if isEnum(f.TypeName, schema) {
				enumNames[f.TypeName] = true
			}
		}
	}
	if len(enumNames) > 0 {
		names := make([]string, 0, len(enumNames))
		for n := range enumNames {
			names = append(names, n)
		}
		sort.Strings(names)
		b.WriteString(fmt.Sprintf("import { %s } from './enums';\n\n", strings.Join(names, ", ")))
	}

	for _, obj := range objects {
		b.WriteString(fmt.Sprintf("/** GraphQL type: %s */\n", obj.Name))
		b.WriteString(fmt.Sprintf("export interface %s {\n", obj.Name))
		for _, f := range obj.Fields {
			tsType := fieldTSType(f)
			optional := ""
			if !f.NonNull {
				optional = "?"
			}
			b.WriteString(fmt.Sprintf("  %s%s: %s;\n", toCamelCase(f.Name), optional, tsType))
		}
		b.WriteString("}\n\n")
	}

	path := filepath.Join(outDir, "src", "models", "models.ts")
	return writeFile(path, b.String())
}
