package typescript

import (
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writePackageJSON generates package.json for the TypeScript npm package.
func writePackageJSON(_ *parser.Schema, outDir string) error {
	content := `{
  "name": "masterfabric-api",
  "version": "0.1.0",
  "description": "Auto-generated TypeScript GraphQL client for the MasterFabric API. Re-generate by running: masterfabric_go generate typescript",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "tsc",
    "prepublishOnly": "npm run build"
  },
  "dependencies": {},
  "devDependencies": {
    "typescript": "^5.3.3"
  },
  "engines": {
    "node": ">=18.0.0"
  },
  "license": "MIT"
}
`
	path := filepath.Join(outDir, "package.json")
	return writeFile(path, content)
}

// writeTsConfig generates tsconfig.json for the TypeScript package.
func writeTsConfig(_ *parser.Schema, outDir string) error {
	content := `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "CommonJS",
    "lib": ["ES2022"],
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
`
	path := filepath.Join(outDir, "tsconfig.json")
	return writeFile(path, content)
}

// writeBarrel generates src/index.ts — the single barrel export file.
func writeBarrel(schema *parser.Schema, outDir string) error {
	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate typescript\n")
	b.WriteString("// Package: masterfabric-api\n")
	b.WriteString("//\n")
	b.WriteString("// Import this single file to get access to all models,\n")
	b.WriteString("// document strings, and the typed client.\n\n")
	b.WriteString("// Models\n")
	b.WriteString("export * from './models/enums';\n")
	b.WriteString("export * from './models/inputs';\n")
	b.WriteString("export * from './models/models';\n\n")
	b.WriteString("// GraphQL document strings\n")
	b.WriteString("export { MasterFabricDocuments } from './queries/documents';\n\n")
	b.WriteString("// Typed client\n")
	b.WriteString("export { MasterFabricClient, MasterFabricException } from './client/MasterFabricClient';\n")
	b.WriteString("export type { GraphQLErrorDetail } from './client/MasterFabricClient';\n")

	path := filepath.Join(outDir, "src", "index.ts")
	return writeFile(path, b.String())
}
