package typescript

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/masterfabric/masterfabric_go_basic/internal/codegen/parser"
)

// writeDocuments generates src/queries/documents.ts with GraphQL operation
// string constants for every query and mutation.
func writeDocuments(schema *parser.Schema, outDir string) error {
	var b strings.Builder
	b.WriteString("// GENERATED CODE — DO NOT EDIT BY HAND\n")
	b.WriteString("// Generated by masterfabric_go generate typescript\n\n")
	b.WriteString("/** Pre-built GraphQL operation strings for every query and mutation. */\n")
	b.WriteString("export const MasterFabricDocuments = {\n")

	// Queries
	for _, q := range schema.Queries {
		if isIntrospectionField(q.Name) {
			continue
		}
		constName := toCamelCase(q.Name) + "Query"
		selectionSet := buildSelectionSet(q.ReturnType, schema)
		doc := buildQueryDocument(q, selectionSet)
		b.WriteString(fmt.Sprintf("  /** Query: %s */\n", q.Name))
		b.WriteString(fmt.Sprintf("  %s: `\n%s\n  `,\n\n", constName, doc))
	}

	// Mutations
	for _, m := range schema.Mutations {
		if isIntrospectionField(m.Name) {
			continue
		}
		constName := toCamelCase(m.Name) + "Mutation"
		selectionSet := buildSelectionSet(m.ReturnType, schema)
		doc := buildMutationDocument(m, selectionSet)
		b.WriteString(fmt.Sprintf("  /** Mutation: %s */\n", m.Name))
		b.WriteString(fmt.Sprintf("  %s: `\n%s\n  `,\n\n", constName, doc))
	}

	b.WriteString("} as const;\n")

	path := filepath.Join(outDir, "src", "queries", "documents.ts")
	return writeFile(path, b.String())
}

// buildQueryDocument emits a full GraphQL query string.
func buildQueryDocument(op *parser.Operation, selectionSet string) string {
	var b strings.Builder
	opName := strings.ToUpper(op.Name[:1]) + op.Name[1:]

	if len(op.Args) == 0 {
		b.WriteString(fmt.Sprintf("    query %s {\n", opName))
		if selectionSet != "" {
			b.WriteString(fmt.Sprintf("      %s %s\n", op.Name, selectionSet))
		} else {
			b.WriteString(fmt.Sprintf("      %s\n", op.Name))
		}
		b.WriteString("    }")
		return b.String()
	}

	varDecls, callArgs := buildArgStrings(op.Args)
	b.WriteString(fmt.Sprintf("    query %s(%s) {\n", opName, varDecls))
	if selectionSet != "" {
		b.WriteString(fmt.Sprintf("      %s(%s) %s\n", op.Name, callArgs, selectionSet))
	} else {
		b.WriteString(fmt.Sprintf("      %s(%s)\n", op.Name, callArgs))
	}
	b.WriteString("    }")
	return b.String()
}

// buildMutationDocument emits a full GraphQL mutation string.
func buildMutationDocument(op *parser.Operation, selectionSet string) string {
	var b strings.Builder
	opName := strings.ToUpper(op.Name[:1]) + op.Name[1:]

	if len(op.Args) == 0 {
		b.WriteString(fmt.Sprintf("    mutation %s {\n", opName))
		if selectionSet != "" {
			b.WriteString(fmt.Sprintf("      %s %s\n", op.Name, selectionSet))
		} else {
			b.WriteString(fmt.Sprintf("      %s\n", op.Name))
		}
		b.WriteString("    }")
		return b.String()
	}

	varDecls, callArgs := buildArgStrings(op.Args)
	b.WriteString(fmt.Sprintf("    mutation %s(%s) {\n", opName, varDecls))
	if selectionSet != "" {
		b.WriteString(fmt.Sprintf("      %s(%s) %s\n", op.Name, callArgs, selectionSet))
	} else {
		b.WriteString(fmt.Sprintf("      %s(%s)\n", op.Name, callArgs))
	}
	b.WriteString("    }")
	return b.String()
}

// buildArgStrings returns ($var: Type!, ...) and (arg: $var, ...) strings.
func buildArgStrings(args []*parser.Argument) (varDecls, callArgs string) {
	var decls, calls []string
	for _, a := range args {
		suffix := ""
		if a.NonNull {
			suffix = "!"
		}
		decls = append(decls, fmt.Sprintf("$%s: %s%s", a.Name, a.TypeName, suffix))
		calls = append(calls, fmt.Sprintf("%s: $%s", a.Name, a.Name))
	}
	return strings.Join(decls, ", "), strings.Join(calls, ", ")
}

// buildSelectionSet builds a minimal { ... } selection set for the return type.
func buildSelectionSet(typeName string, schema *parser.Schema) string {
	if typeName == "" || typeName == "Boolean" || isScalar(typeName) {
		return ""
	}

	obj := findObject(typeName, schema)
	if obj == nil {
		return ""
	}

	var lines []string
	lines = append(lines, "{")
	for _, f := range obj.Fields {
		if isScalar(f.TypeName) || f.TypeName == "" {
			lines = append(lines, "        "+f.Name)
		} else {
			nested := findObject(f.TypeName, schema)
			if nested != nil {
				lines = append(lines, "        "+f.Name+" {")
				for _, nf := range nested.Fields {
					if isScalar(nf.TypeName) || nf.TypeName == "" {
						lines = append(lines, "          "+nf.Name)
					}
				}
				lines = append(lines, "        }")
			} else {
				lines = append(lines, "        "+f.Name)
			}
		}
	}
	lines = append(lines, "      }")
	return strings.Join(lines, "\n")
}

func findObject(name string, schema *parser.Schema) *parser.ObjectType {
	for _, o := range schema.Objects {
		if o.Name == name {
			return o
		}
	}
	return nil
}
